// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

public interface CircuitBreakerStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opensearch.protobufs.services.CircuitBreakerStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 limit = 2 [json_name = "limit"];</code>
   * @return The limit.
   */
  long getLimit();

  /**
   * <code>int64 estimated = 3 [json_name = "estimated"];</code>
   * @return The estimated.
   */
  long getEstimated();

  /**
   * <code>double overhead = 4 [json_name = "overhead"];</code>
   * @return The overhead.
   */
  double getOverhead();

  /**
   * <code>int64 tripped = 5 [json_name = "tripped"];</code>
   * @return The tripped.
   */
  long getTripped();
}
