// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

/**
 * Protobuf type {@code org.opensearch.protobufs.services.CircuitBreakerMetrics}
 */
public final class CircuitBreakerMetrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.opensearch.protobufs.services.CircuitBreakerMetrics)
    CircuitBreakerMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CircuitBreakerMetrics.newBuilder() to construct.
  private CircuitBreakerMetrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CircuitBreakerMetrics() {
    breakers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CircuitBreakerMetrics();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_CircuitBreakerMetrics_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_CircuitBreakerMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opensearch.protobufs.services.CircuitBreakerMetrics.class, org.opensearch.protobufs.services.CircuitBreakerMetrics.Builder.class);
  }

  public static final int BREAKERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.opensearch.protobufs.services.CircuitBreakerStats> breakers_;
  /**
   * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
   */
  @java.lang.Override
  public java.util.List<org.opensearch.protobufs.services.CircuitBreakerStats> getBreakersList() {
    return breakers_;
  }
  /**
   * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.opensearch.protobufs.services.CircuitBreakerStatsOrBuilder> 
      getBreakersOrBuilderList() {
    return breakers_;
  }
  /**
   * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
   */
  @java.lang.Override
  public int getBreakersCount() {
    return breakers_.size();
  }
  /**
   * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.CircuitBreakerStats getBreakers(int index) {
    return breakers_.get(index);
  }
  /**
   * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.CircuitBreakerStatsOrBuilder getBreakersOrBuilder(
      int index) {
    return breakers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < breakers_.size(); i++) {
      output.writeMessage(1, breakers_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < breakers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, breakers_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opensearch.protobufs.services.CircuitBreakerMetrics)) {
      return super.equals(obj);
    }
    org.opensearch.protobufs.services.CircuitBreakerMetrics other = (org.opensearch.protobufs.services.CircuitBreakerMetrics) obj;

    if (!getBreakersList()
        .equals(other.getBreakersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBreakersCount() > 0) {
      hash = (37 * hash) + BREAKERS_FIELD_NUMBER;
      hash = (53 * hash) + getBreakersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opensearch.protobufs.services.CircuitBreakerMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.CircuitBreakerMetrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.CircuitBreakerMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.CircuitBreakerMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.CircuitBreakerMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.CircuitBreakerMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.CircuitBreakerMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.CircuitBreakerMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.opensearch.protobufs.services.CircuitBreakerMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.opensearch.protobufs.services.CircuitBreakerMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.CircuitBreakerMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.CircuitBreakerMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opensearch.protobufs.services.CircuitBreakerMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.opensearch.protobufs.services.CircuitBreakerMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.opensearch.protobufs.services.CircuitBreakerMetrics)
      org.opensearch.protobufs.services.CircuitBreakerMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_CircuitBreakerMetrics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_CircuitBreakerMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opensearch.protobufs.services.CircuitBreakerMetrics.class, org.opensearch.protobufs.services.CircuitBreakerMetrics.Builder.class);
    }

    // Construct using org.opensearch.protobufs.services.CircuitBreakerMetrics.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (breakersBuilder_ == null) {
        breakers_ = java.util.Collections.emptyList();
      } else {
        breakers_ = null;
        breakersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_CircuitBreakerMetrics_descriptor;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.CircuitBreakerMetrics getDefaultInstanceForType() {
      return org.opensearch.protobufs.services.CircuitBreakerMetrics.getDefaultInstance();
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.CircuitBreakerMetrics build() {
      org.opensearch.protobufs.services.CircuitBreakerMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.CircuitBreakerMetrics buildPartial() {
      org.opensearch.protobufs.services.CircuitBreakerMetrics result = new org.opensearch.protobufs.services.CircuitBreakerMetrics(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.opensearch.protobufs.services.CircuitBreakerMetrics result) {
      if (breakersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          breakers_ = java.util.Collections.unmodifiableList(breakers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.breakers_ = breakers_;
      } else {
        result.breakers_ = breakersBuilder_.build();
      }
    }

    private void buildPartial0(org.opensearch.protobufs.services.CircuitBreakerMetrics result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opensearch.protobufs.services.CircuitBreakerMetrics) {
        return mergeFrom((org.opensearch.protobufs.services.CircuitBreakerMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opensearch.protobufs.services.CircuitBreakerMetrics other) {
      if (other == org.opensearch.protobufs.services.CircuitBreakerMetrics.getDefaultInstance()) return this;
      if (breakersBuilder_ == null) {
        if (!other.breakers_.isEmpty()) {
          if (breakers_.isEmpty()) {
            breakers_ = other.breakers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBreakersIsMutable();
            breakers_.addAll(other.breakers_);
          }
          onChanged();
        }
      } else {
        if (!other.breakers_.isEmpty()) {
          if (breakersBuilder_.isEmpty()) {
            breakersBuilder_.dispose();
            breakersBuilder_ = null;
            breakers_ = other.breakers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            breakersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBreakersFieldBuilder() : null;
          } else {
            breakersBuilder_.addAllMessages(other.breakers_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.opensearch.protobufs.services.CircuitBreakerStats m =
                  input.readMessage(
                      org.opensearch.protobufs.services.CircuitBreakerStats.parser(),
                      extensionRegistry);
              if (breakersBuilder_ == null) {
                ensureBreakersIsMutable();
                breakers_.add(m);
              } else {
                breakersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.opensearch.protobufs.services.CircuitBreakerStats> breakers_ =
      java.util.Collections.emptyList();
    private void ensureBreakersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        breakers_ = new java.util.ArrayList<org.opensearch.protobufs.services.CircuitBreakerStats>(breakers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.opensearch.protobufs.services.CircuitBreakerStats, org.opensearch.protobufs.services.CircuitBreakerStats.Builder, org.opensearch.protobufs.services.CircuitBreakerStatsOrBuilder> breakersBuilder_;

    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public java.util.List<org.opensearch.protobufs.services.CircuitBreakerStats> getBreakersList() {
      if (breakersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(breakers_);
      } else {
        return breakersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public int getBreakersCount() {
      if (breakersBuilder_ == null) {
        return breakers_.size();
      } else {
        return breakersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public org.opensearch.protobufs.services.CircuitBreakerStats getBreakers(int index) {
      if (breakersBuilder_ == null) {
        return breakers_.get(index);
      } else {
        return breakersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public Builder setBreakers(
        int index, org.opensearch.protobufs.services.CircuitBreakerStats value) {
      if (breakersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBreakersIsMutable();
        breakers_.set(index, value);
        onChanged();
      } else {
        breakersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public Builder setBreakers(
        int index, org.opensearch.protobufs.services.CircuitBreakerStats.Builder builderForValue) {
      if (breakersBuilder_ == null) {
        ensureBreakersIsMutable();
        breakers_.set(index, builderForValue.build());
        onChanged();
      } else {
        breakersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public Builder addBreakers(org.opensearch.protobufs.services.CircuitBreakerStats value) {
      if (breakersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBreakersIsMutable();
        breakers_.add(value);
        onChanged();
      } else {
        breakersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public Builder addBreakers(
        int index, org.opensearch.protobufs.services.CircuitBreakerStats value) {
      if (breakersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBreakersIsMutable();
        breakers_.add(index, value);
        onChanged();
      } else {
        breakersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public Builder addBreakers(
        org.opensearch.protobufs.services.CircuitBreakerStats.Builder builderForValue) {
      if (breakersBuilder_ == null) {
        ensureBreakersIsMutable();
        breakers_.add(builderForValue.build());
        onChanged();
      } else {
        breakersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public Builder addBreakers(
        int index, org.opensearch.protobufs.services.CircuitBreakerStats.Builder builderForValue) {
      if (breakersBuilder_ == null) {
        ensureBreakersIsMutable();
        breakers_.add(index, builderForValue.build());
        onChanged();
      } else {
        breakersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public Builder addAllBreakers(
        java.lang.Iterable<? extends org.opensearch.protobufs.services.CircuitBreakerStats> values) {
      if (breakersBuilder_ == null) {
        ensureBreakersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, breakers_);
        onChanged();
      } else {
        breakersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public Builder clearBreakers() {
      if (breakersBuilder_ == null) {
        breakers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        breakersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public Builder removeBreakers(int index) {
      if (breakersBuilder_ == null) {
        ensureBreakersIsMutable();
        breakers_.remove(index);
        onChanged();
      } else {
        breakersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public org.opensearch.protobufs.services.CircuitBreakerStats.Builder getBreakersBuilder(
        int index) {
      return getBreakersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public org.opensearch.protobufs.services.CircuitBreakerStatsOrBuilder getBreakersOrBuilder(
        int index) {
      if (breakersBuilder_ == null) {
        return breakers_.get(index);  } else {
        return breakersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public java.util.List<? extends org.opensearch.protobufs.services.CircuitBreakerStatsOrBuilder> 
         getBreakersOrBuilderList() {
      if (breakersBuilder_ != null) {
        return breakersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(breakers_);
      }
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public org.opensearch.protobufs.services.CircuitBreakerStats.Builder addBreakersBuilder() {
      return getBreakersFieldBuilder().addBuilder(
          org.opensearch.protobufs.services.CircuitBreakerStats.getDefaultInstance());
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public org.opensearch.protobufs.services.CircuitBreakerStats.Builder addBreakersBuilder(
        int index) {
      return getBreakersFieldBuilder().addBuilder(
          index, org.opensearch.protobufs.services.CircuitBreakerStats.getDefaultInstance());
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
     */
    public java.util.List<org.opensearch.protobufs.services.CircuitBreakerStats.Builder> 
         getBreakersBuilderList() {
      return getBreakersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.opensearch.protobufs.services.CircuitBreakerStats, org.opensearch.protobufs.services.CircuitBreakerStats.Builder, org.opensearch.protobufs.services.CircuitBreakerStatsOrBuilder> 
        getBreakersFieldBuilder() {
      if (breakersBuilder_ == null) {
        breakersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.opensearch.protobufs.services.CircuitBreakerStats, org.opensearch.protobufs.services.CircuitBreakerStats.Builder, org.opensearch.protobufs.services.CircuitBreakerStatsOrBuilder>(
                breakers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        breakers_ = null;
      }
      return breakersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.opensearch.protobufs.services.CircuitBreakerMetrics)
  }

  // @@protoc_insertion_point(class_scope:org.opensearch.protobufs.services.CircuitBreakerMetrics)
  private static final org.opensearch.protobufs.services.CircuitBreakerMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opensearch.protobufs.services.CircuitBreakerMetrics();
  }

  public static org.opensearch.protobufs.services.CircuitBreakerMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CircuitBreakerMetrics>
      PARSER = new com.google.protobuf.AbstractParser<CircuitBreakerMetrics>() {
    @java.lang.Override
    public CircuitBreakerMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CircuitBreakerMetrics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CircuitBreakerMetrics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opensearch.protobufs.services.CircuitBreakerMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

