// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

public interface CircuitBreakerMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opensearch.protobufs.services.CircuitBreakerMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
   */
  java.util.List<org.opensearch.protobufs.services.CircuitBreakerStats> 
      getBreakersList();
  /**
   * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
   */
  org.opensearch.protobufs.services.CircuitBreakerStats getBreakers(int index);
  /**
   * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
   */
  int getBreakersCount();
  /**
   * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
   */
  java.util.List<? extends org.opensearch.protobufs.services.CircuitBreakerStatsOrBuilder> 
      getBreakersOrBuilderList();
  /**
   * <code>repeated .org.opensearch.protobufs.services.CircuitBreakerStats breakers = 1 [json_name = "breakers"];</code>
   */
  org.opensearch.protobufs.services.CircuitBreakerStatsOrBuilder getBreakersOrBuilder(
      int index);
}
