// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

public interface IndexingPressureMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opensearch.protobufs.services.IndexingPressureMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 current_coordinating_bytes = 1 [json_name = "currentCoordinatingBytes"];</code>
   * @return The currentCoordinatingBytes.
   */
  long getCurrentCoordinatingBytes();

  /**
   * <code>int64 current_primary_bytes = 2 [json_name = "currentPrimaryBytes"];</code>
   * @return The currentPrimaryBytes.
   */
  long getCurrentPrimaryBytes();

  /**
   * <code>int64 current_replica_bytes = 3 [json_name = "currentReplicaBytes"];</code>
   * @return The currentReplicaBytes.
   */
  long getCurrentReplicaBytes();

  /**
   * <code>int64 total_coordinating_rejected = 4 [json_name = "totalCoordinatingRejected"];</code>
   * @return The totalCoordinatingRejected.
   */
  long getTotalCoordinatingRejected();

  /**
   * <code>int64 total_primary_rejected = 5 [json_name = "totalPrimaryRejected"];</code>
   * @return The totalPrimaryRejected.
   */
  long getTotalPrimaryRejected();

  /**
   * <code>int64 total_replica_rejected = 6 [json_name = "totalReplicaRejected"];</code>
   * @return The totalReplicaRejected.
   */
  long getTotalReplicaRejected();

  /**
   * <code>int64 memory_limit = 7 [json_name = "memoryLimit"];</code>
   * @return The memoryLimit.
   */
  long getMemoryLimit();
}
