// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

/**
 * Protobuf type {@code org.opensearch.protobufs.services.IndexingPressureMetrics}
 */
public final class IndexingPressureMetrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.opensearch.protobufs.services.IndexingPressureMetrics)
    IndexingPressureMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IndexingPressureMetrics.newBuilder() to construct.
  private IndexingPressureMetrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IndexingPressureMetrics() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IndexingPressureMetrics();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_IndexingPressureMetrics_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_IndexingPressureMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opensearch.protobufs.services.IndexingPressureMetrics.class, org.opensearch.protobufs.services.IndexingPressureMetrics.Builder.class);
  }

  public static final int CURRENT_COORDINATING_BYTES_FIELD_NUMBER = 1;
  private long currentCoordinatingBytes_ = 0L;
  /**
   * <code>int64 current_coordinating_bytes = 1 [json_name = "currentCoordinatingBytes"];</code>
   * @return The currentCoordinatingBytes.
   */
  @java.lang.Override
  public long getCurrentCoordinatingBytes() {
    return currentCoordinatingBytes_;
  }

  public static final int CURRENT_PRIMARY_BYTES_FIELD_NUMBER = 2;
  private long currentPrimaryBytes_ = 0L;
  /**
   * <code>int64 current_primary_bytes = 2 [json_name = "currentPrimaryBytes"];</code>
   * @return The currentPrimaryBytes.
   */
  @java.lang.Override
  public long getCurrentPrimaryBytes() {
    return currentPrimaryBytes_;
  }

  public static final int CURRENT_REPLICA_BYTES_FIELD_NUMBER = 3;
  private long currentReplicaBytes_ = 0L;
  /**
   * <code>int64 current_replica_bytes = 3 [json_name = "currentReplicaBytes"];</code>
   * @return The currentReplicaBytes.
   */
  @java.lang.Override
  public long getCurrentReplicaBytes() {
    return currentReplicaBytes_;
  }

  public static final int TOTAL_COORDINATING_REJECTED_FIELD_NUMBER = 4;
  private long totalCoordinatingRejected_ = 0L;
  /**
   * <code>int64 total_coordinating_rejected = 4 [json_name = "totalCoordinatingRejected"];</code>
   * @return The totalCoordinatingRejected.
   */
  @java.lang.Override
  public long getTotalCoordinatingRejected() {
    return totalCoordinatingRejected_;
  }

  public static final int TOTAL_PRIMARY_REJECTED_FIELD_NUMBER = 5;
  private long totalPrimaryRejected_ = 0L;
  /**
   * <code>int64 total_primary_rejected = 5 [json_name = "totalPrimaryRejected"];</code>
   * @return The totalPrimaryRejected.
   */
  @java.lang.Override
  public long getTotalPrimaryRejected() {
    return totalPrimaryRejected_;
  }

  public static final int TOTAL_REPLICA_REJECTED_FIELD_NUMBER = 6;
  private long totalReplicaRejected_ = 0L;
  /**
   * <code>int64 total_replica_rejected = 6 [json_name = "totalReplicaRejected"];</code>
   * @return The totalReplicaRejected.
   */
  @java.lang.Override
  public long getTotalReplicaRejected() {
    return totalReplicaRejected_;
  }

  public static final int MEMORY_LIMIT_FIELD_NUMBER = 7;
  private long memoryLimit_ = 0L;
  /**
   * <code>int64 memory_limit = 7 [json_name = "memoryLimit"];</code>
   * @return The memoryLimit.
   */
  @java.lang.Override
  public long getMemoryLimit() {
    return memoryLimit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentCoordinatingBytes_ != 0L) {
      output.writeInt64(1, currentCoordinatingBytes_);
    }
    if (currentPrimaryBytes_ != 0L) {
      output.writeInt64(2, currentPrimaryBytes_);
    }
    if (currentReplicaBytes_ != 0L) {
      output.writeInt64(3, currentReplicaBytes_);
    }
    if (totalCoordinatingRejected_ != 0L) {
      output.writeInt64(4, totalCoordinatingRejected_);
    }
    if (totalPrimaryRejected_ != 0L) {
      output.writeInt64(5, totalPrimaryRejected_);
    }
    if (totalReplicaRejected_ != 0L) {
      output.writeInt64(6, totalReplicaRejected_);
    }
    if (memoryLimit_ != 0L) {
      output.writeInt64(7, memoryLimit_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentCoordinatingBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, currentCoordinatingBytes_);
    }
    if (currentPrimaryBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, currentPrimaryBytes_);
    }
    if (currentReplicaBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, currentReplicaBytes_);
    }
    if (totalCoordinatingRejected_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, totalCoordinatingRejected_);
    }
    if (totalPrimaryRejected_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, totalPrimaryRejected_);
    }
    if (totalReplicaRejected_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, totalReplicaRejected_);
    }
    if (memoryLimit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, memoryLimit_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opensearch.protobufs.services.IndexingPressureMetrics)) {
      return super.equals(obj);
    }
    org.opensearch.protobufs.services.IndexingPressureMetrics other = (org.opensearch.protobufs.services.IndexingPressureMetrics) obj;

    if (getCurrentCoordinatingBytes()
        != other.getCurrentCoordinatingBytes()) return false;
    if (getCurrentPrimaryBytes()
        != other.getCurrentPrimaryBytes()) return false;
    if (getCurrentReplicaBytes()
        != other.getCurrentReplicaBytes()) return false;
    if (getTotalCoordinatingRejected()
        != other.getTotalCoordinatingRejected()) return false;
    if (getTotalPrimaryRejected()
        != other.getTotalPrimaryRejected()) return false;
    if (getTotalReplicaRejected()
        != other.getTotalReplicaRejected()) return false;
    if (getMemoryLimit()
        != other.getMemoryLimit()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENT_COORDINATING_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentCoordinatingBytes());
    hash = (37 * hash) + CURRENT_PRIMARY_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentPrimaryBytes());
    hash = (37 * hash) + CURRENT_REPLICA_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentReplicaBytes());
    hash = (37 * hash) + TOTAL_COORDINATING_REJECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalCoordinatingRejected());
    hash = (37 * hash) + TOTAL_PRIMARY_REJECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalPrimaryRejected());
    hash = (37 * hash) + TOTAL_REPLICA_REJECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalReplicaRejected());
    hash = (37 * hash) + MEMORY_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMemoryLimit());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opensearch.protobufs.services.IndexingPressureMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.IndexingPressureMetrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.IndexingPressureMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.IndexingPressureMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.IndexingPressureMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.IndexingPressureMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.IndexingPressureMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.IndexingPressureMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.opensearch.protobufs.services.IndexingPressureMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.opensearch.protobufs.services.IndexingPressureMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.IndexingPressureMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.IndexingPressureMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opensearch.protobufs.services.IndexingPressureMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.opensearch.protobufs.services.IndexingPressureMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.opensearch.protobufs.services.IndexingPressureMetrics)
      org.opensearch.protobufs.services.IndexingPressureMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_IndexingPressureMetrics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_IndexingPressureMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opensearch.protobufs.services.IndexingPressureMetrics.class, org.opensearch.protobufs.services.IndexingPressureMetrics.Builder.class);
    }

    // Construct using org.opensearch.protobufs.services.IndexingPressureMetrics.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      currentCoordinatingBytes_ = 0L;
      currentPrimaryBytes_ = 0L;
      currentReplicaBytes_ = 0L;
      totalCoordinatingRejected_ = 0L;
      totalPrimaryRejected_ = 0L;
      totalReplicaRejected_ = 0L;
      memoryLimit_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_IndexingPressureMetrics_descriptor;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.IndexingPressureMetrics getDefaultInstanceForType() {
      return org.opensearch.protobufs.services.IndexingPressureMetrics.getDefaultInstance();
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.IndexingPressureMetrics build() {
      org.opensearch.protobufs.services.IndexingPressureMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.IndexingPressureMetrics buildPartial() {
      org.opensearch.protobufs.services.IndexingPressureMetrics result = new org.opensearch.protobufs.services.IndexingPressureMetrics(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.opensearch.protobufs.services.IndexingPressureMetrics result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.currentCoordinatingBytes_ = currentCoordinatingBytes_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.currentPrimaryBytes_ = currentPrimaryBytes_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.currentReplicaBytes_ = currentReplicaBytes_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.totalCoordinatingRejected_ = totalCoordinatingRejected_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.totalPrimaryRejected_ = totalPrimaryRejected_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.totalReplicaRejected_ = totalReplicaRejected_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.memoryLimit_ = memoryLimit_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opensearch.protobufs.services.IndexingPressureMetrics) {
        return mergeFrom((org.opensearch.protobufs.services.IndexingPressureMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opensearch.protobufs.services.IndexingPressureMetrics other) {
      if (other == org.opensearch.protobufs.services.IndexingPressureMetrics.getDefaultInstance()) return this;
      if (other.getCurrentCoordinatingBytes() != 0L) {
        setCurrentCoordinatingBytes(other.getCurrentCoordinatingBytes());
      }
      if (other.getCurrentPrimaryBytes() != 0L) {
        setCurrentPrimaryBytes(other.getCurrentPrimaryBytes());
      }
      if (other.getCurrentReplicaBytes() != 0L) {
        setCurrentReplicaBytes(other.getCurrentReplicaBytes());
      }
      if (other.getTotalCoordinatingRejected() != 0L) {
        setTotalCoordinatingRejected(other.getTotalCoordinatingRejected());
      }
      if (other.getTotalPrimaryRejected() != 0L) {
        setTotalPrimaryRejected(other.getTotalPrimaryRejected());
      }
      if (other.getTotalReplicaRejected() != 0L) {
        setTotalReplicaRejected(other.getTotalReplicaRejected());
      }
      if (other.getMemoryLimit() != 0L) {
        setMemoryLimit(other.getMemoryLimit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              currentCoordinatingBytes_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              currentPrimaryBytes_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              currentReplicaBytes_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              totalCoordinatingRejected_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              totalPrimaryRejected_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              totalReplicaRejected_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              memoryLimit_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long currentCoordinatingBytes_ ;
    /**
     * <code>int64 current_coordinating_bytes = 1 [json_name = "currentCoordinatingBytes"];</code>
     * @return The currentCoordinatingBytes.
     */
    @java.lang.Override
    public long getCurrentCoordinatingBytes() {
      return currentCoordinatingBytes_;
    }
    /**
     * <code>int64 current_coordinating_bytes = 1 [json_name = "currentCoordinatingBytes"];</code>
     * @param value The currentCoordinatingBytes to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentCoordinatingBytes(long value) {

      currentCoordinatingBytes_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 current_coordinating_bytes = 1 [json_name = "currentCoordinatingBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentCoordinatingBytes() {
      bitField0_ = (bitField0_ & ~0x00000001);
      currentCoordinatingBytes_ = 0L;
      onChanged();
      return this;
    }

    private long currentPrimaryBytes_ ;
    /**
     * <code>int64 current_primary_bytes = 2 [json_name = "currentPrimaryBytes"];</code>
     * @return The currentPrimaryBytes.
     */
    @java.lang.Override
    public long getCurrentPrimaryBytes() {
      return currentPrimaryBytes_;
    }
    /**
     * <code>int64 current_primary_bytes = 2 [json_name = "currentPrimaryBytes"];</code>
     * @param value The currentPrimaryBytes to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentPrimaryBytes(long value) {

      currentPrimaryBytes_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 current_primary_bytes = 2 [json_name = "currentPrimaryBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentPrimaryBytes() {
      bitField0_ = (bitField0_ & ~0x00000002);
      currentPrimaryBytes_ = 0L;
      onChanged();
      return this;
    }

    private long currentReplicaBytes_ ;
    /**
     * <code>int64 current_replica_bytes = 3 [json_name = "currentReplicaBytes"];</code>
     * @return The currentReplicaBytes.
     */
    @java.lang.Override
    public long getCurrentReplicaBytes() {
      return currentReplicaBytes_;
    }
    /**
     * <code>int64 current_replica_bytes = 3 [json_name = "currentReplicaBytes"];</code>
     * @param value The currentReplicaBytes to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentReplicaBytes(long value) {

      currentReplicaBytes_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 current_replica_bytes = 3 [json_name = "currentReplicaBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentReplicaBytes() {
      bitField0_ = (bitField0_ & ~0x00000004);
      currentReplicaBytes_ = 0L;
      onChanged();
      return this;
    }

    private long totalCoordinatingRejected_ ;
    /**
     * <code>int64 total_coordinating_rejected = 4 [json_name = "totalCoordinatingRejected"];</code>
     * @return The totalCoordinatingRejected.
     */
    @java.lang.Override
    public long getTotalCoordinatingRejected() {
      return totalCoordinatingRejected_;
    }
    /**
     * <code>int64 total_coordinating_rejected = 4 [json_name = "totalCoordinatingRejected"];</code>
     * @param value The totalCoordinatingRejected to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCoordinatingRejected(long value) {

      totalCoordinatingRejected_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total_coordinating_rejected = 4 [json_name = "totalCoordinatingRejected"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCoordinatingRejected() {
      bitField0_ = (bitField0_ & ~0x00000008);
      totalCoordinatingRejected_ = 0L;
      onChanged();
      return this;
    }

    private long totalPrimaryRejected_ ;
    /**
     * <code>int64 total_primary_rejected = 5 [json_name = "totalPrimaryRejected"];</code>
     * @return The totalPrimaryRejected.
     */
    @java.lang.Override
    public long getTotalPrimaryRejected() {
      return totalPrimaryRejected_;
    }
    /**
     * <code>int64 total_primary_rejected = 5 [json_name = "totalPrimaryRejected"];</code>
     * @param value The totalPrimaryRejected to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPrimaryRejected(long value) {

      totalPrimaryRejected_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total_primary_rejected = 5 [json_name = "totalPrimaryRejected"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPrimaryRejected() {
      bitField0_ = (bitField0_ & ~0x00000010);
      totalPrimaryRejected_ = 0L;
      onChanged();
      return this;
    }

    private long totalReplicaRejected_ ;
    /**
     * <code>int64 total_replica_rejected = 6 [json_name = "totalReplicaRejected"];</code>
     * @return The totalReplicaRejected.
     */
    @java.lang.Override
    public long getTotalReplicaRejected() {
      return totalReplicaRejected_;
    }
    /**
     * <code>int64 total_replica_rejected = 6 [json_name = "totalReplicaRejected"];</code>
     * @param value The totalReplicaRejected to set.
     * @return This builder for chaining.
     */
    public Builder setTotalReplicaRejected(long value) {

      totalReplicaRejected_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total_replica_rejected = 6 [json_name = "totalReplicaRejected"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalReplicaRejected() {
      bitField0_ = (bitField0_ & ~0x00000020);
      totalReplicaRejected_ = 0L;
      onChanged();
      return this;
    }

    private long memoryLimit_ ;
    /**
     * <code>int64 memory_limit = 7 [json_name = "memoryLimit"];</code>
     * @return The memoryLimit.
     */
    @java.lang.Override
    public long getMemoryLimit() {
      return memoryLimit_;
    }
    /**
     * <code>int64 memory_limit = 7 [json_name = "memoryLimit"];</code>
     * @param value The memoryLimit to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryLimit(long value) {

      memoryLimit_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 memory_limit = 7 [json_name = "memoryLimit"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryLimit() {
      bitField0_ = (bitField0_ & ~0x00000040);
      memoryLimit_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.opensearch.protobufs.services.IndexingPressureMetrics)
  }

  // @@protoc_insertion_point(class_scope:org.opensearch.protobufs.services.IndexingPressureMetrics)
  private static final org.opensearch.protobufs.services.IndexingPressureMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opensearch.protobufs.services.IndexingPressureMetrics();
  }

  public static org.opensearch.protobufs.services.IndexingPressureMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IndexingPressureMetrics>
      PARSER = new com.google.protobuf.AbstractParser<IndexingPressureMetrics>() {
    @java.lang.Override
    public IndexingPressureMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IndexingPressureMetrics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IndexingPressureMetrics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opensearch.protobufs.services.IndexingPressureMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

