// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

public interface JvmMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opensearch.protobufs.services.JvmMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 heap_used_bytes = 1 [json_name = "heapUsedBytes"];</code>
   * @return The heapUsedBytes.
   */
  long getHeapUsedBytes();

  /**
   * <code>int64 heap_max_bytes = 2 [json_name = "heapMaxBytes"];</code>
   * @return The heapMaxBytes.
   */
  long getHeapMaxBytes();

  /**
   * <code>int64 non_heap_used_bytes = 3 [json_name = "nonHeapUsedBytes"];</code>
   * @return The nonHeapUsedBytes.
   */
  long getNonHeapUsedBytes();

  /**
   * <code>int64 gc_count = 4 [json_name = "gcCount"];</code>
   * @return The gcCount.
   */
  long getGcCount();

  /**
   * <code>int64 gc_time_millis = 5 [json_name = "gcTimeMillis"];</code>
   * @return The gcTimeMillis.
   */
  long getGcTimeMillis();
}
