// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

/**
 * Protobuf type {@code org.opensearch.protobufs.services.JvmMetrics}
 */
public final class JvmMetrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.opensearch.protobufs.services.JvmMetrics)
    JvmMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JvmMetrics.newBuilder() to construct.
  private JvmMetrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JvmMetrics() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JvmMetrics();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_JvmMetrics_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_JvmMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opensearch.protobufs.services.JvmMetrics.class, org.opensearch.protobufs.services.JvmMetrics.Builder.class);
  }

  public static final int HEAP_USED_BYTES_FIELD_NUMBER = 1;
  private long heapUsedBytes_ = 0L;
  /**
   * <code>int64 heap_used_bytes = 1 [json_name = "heapUsedBytes"];</code>
   * @return The heapUsedBytes.
   */
  @java.lang.Override
  public long getHeapUsedBytes() {
    return heapUsedBytes_;
  }

  public static final int HEAP_MAX_BYTES_FIELD_NUMBER = 2;
  private long heapMaxBytes_ = 0L;
  /**
   * <code>int64 heap_max_bytes = 2 [json_name = "heapMaxBytes"];</code>
   * @return The heapMaxBytes.
   */
  @java.lang.Override
  public long getHeapMaxBytes() {
    return heapMaxBytes_;
  }

  public static final int NON_HEAP_USED_BYTES_FIELD_NUMBER = 3;
  private long nonHeapUsedBytes_ = 0L;
  /**
   * <code>int64 non_heap_used_bytes = 3 [json_name = "nonHeapUsedBytes"];</code>
   * @return The nonHeapUsedBytes.
   */
  @java.lang.Override
  public long getNonHeapUsedBytes() {
    return nonHeapUsedBytes_;
  }

  public static final int GC_COUNT_FIELD_NUMBER = 4;
  private long gcCount_ = 0L;
  /**
   * <code>int64 gc_count = 4 [json_name = "gcCount"];</code>
   * @return The gcCount.
   */
  @java.lang.Override
  public long getGcCount() {
    return gcCount_;
  }

  public static final int GC_TIME_MILLIS_FIELD_NUMBER = 5;
  private long gcTimeMillis_ = 0L;
  /**
   * <code>int64 gc_time_millis = 5 [json_name = "gcTimeMillis"];</code>
   * @return The gcTimeMillis.
   */
  @java.lang.Override
  public long getGcTimeMillis() {
    return gcTimeMillis_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (heapUsedBytes_ != 0L) {
      output.writeInt64(1, heapUsedBytes_);
    }
    if (heapMaxBytes_ != 0L) {
      output.writeInt64(2, heapMaxBytes_);
    }
    if (nonHeapUsedBytes_ != 0L) {
      output.writeInt64(3, nonHeapUsedBytes_);
    }
    if (gcCount_ != 0L) {
      output.writeInt64(4, gcCount_);
    }
    if (gcTimeMillis_ != 0L) {
      output.writeInt64(5, gcTimeMillis_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (heapUsedBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, heapUsedBytes_);
    }
    if (heapMaxBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, heapMaxBytes_);
    }
    if (nonHeapUsedBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, nonHeapUsedBytes_);
    }
    if (gcCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, gcCount_);
    }
    if (gcTimeMillis_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, gcTimeMillis_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opensearch.protobufs.services.JvmMetrics)) {
      return super.equals(obj);
    }
    org.opensearch.protobufs.services.JvmMetrics other = (org.opensearch.protobufs.services.JvmMetrics) obj;

    if (getHeapUsedBytes()
        != other.getHeapUsedBytes()) return false;
    if (getHeapMaxBytes()
        != other.getHeapMaxBytes()) return false;
    if (getNonHeapUsedBytes()
        != other.getNonHeapUsedBytes()) return false;
    if (getGcCount()
        != other.getGcCount()) return false;
    if (getGcTimeMillis()
        != other.getGcTimeMillis()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HEAP_USED_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHeapUsedBytes());
    hash = (37 * hash) + HEAP_MAX_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHeapMaxBytes());
    hash = (37 * hash) + NON_HEAP_USED_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNonHeapUsedBytes());
    hash = (37 * hash) + GC_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGcCount());
    hash = (37 * hash) + GC_TIME_MILLIS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGcTimeMillis());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opensearch.protobufs.services.JvmMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.JvmMetrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.JvmMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.JvmMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.JvmMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.JvmMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.JvmMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.JvmMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.opensearch.protobufs.services.JvmMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.opensearch.protobufs.services.JvmMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.JvmMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.JvmMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opensearch.protobufs.services.JvmMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.opensearch.protobufs.services.JvmMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.opensearch.protobufs.services.JvmMetrics)
      org.opensearch.protobufs.services.JvmMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_JvmMetrics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_JvmMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opensearch.protobufs.services.JvmMetrics.class, org.opensearch.protobufs.services.JvmMetrics.Builder.class);
    }

    // Construct using org.opensearch.protobufs.services.JvmMetrics.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      heapUsedBytes_ = 0L;
      heapMaxBytes_ = 0L;
      nonHeapUsedBytes_ = 0L;
      gcCount_ = 0L;
      gcTimeMillis_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_JvmMetrics_descriptor;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.JvmMetrics getDefaultInstanceForType() {
      return org.opensearch.protobufs.services.JvmMetrics.getDefaultInstance();
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.JvmMetrics build() {
      org.opensearch.protobufs.services.JvmMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.JvmMetrics buildPartial() {
      org.opensearch.protobufs.services.JvmMetrics result = new org.opensearch.protobufs.services.JvmMetrics(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.opensearch.protobufs.services.JvmMetrics result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.heapUsedBytes_ = heapUsedBytes_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.heapMaxBytes_ = heapMaxBytes_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.nonHeapUsedBytes_ = nonHeapUsedBytes_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.gcCount_ = gcCount_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.gcTimeMillis_ = gcTimeMillis_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opensearch.protobufs.services.JvmMetrics) {
        return mergeFrom((org.opensearch.protobufs.services.JvmMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opensearch.protobufs.services.JvmMetrics other) {
      if (other == org.opensearch.protobufs.services.JvmMetrics.getDefaultInstance()) return this;
      if (other.getHeapUsedBytes() != 0L) {
        setHeapUsedBytes(other.getHeapUsedBytes());
      }
      if (other.getHeapMaxBytes() != 0L) {
        setHeapMaxBytes(other.getHeapMaxBytes());
      }
      if (other.getNonHeapUsedBytes() != 0L) {
        setNonHeapUsedBytes(other.getNonHeapUsedBytes());
      }
      if (other.getGcCount() != 0L) {
        setGcCount(other.getGcCount());
      }
      if (other.getGcTimeMillis() != 0L) {
        setGcTimeMillis(other.getGcTimeMillis());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              heapUsedBytes_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              heapMaxBytes_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              nonHeapUsedBytes_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              gcCount_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              gcTimeMillis_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long heapUsedBytes_ ;
    /**
     * <code>int64 heap_used_bytes = 1 [json_name = "heapUsedBytes"];</code>
     * @return The heapUsedBytes.
     */
    @java.lang.Override
    public long getHeapUsedBytes() {
      return heapUsedBytes_;
    }
    /**
     * <code>int64 heap_used_bytes = 1 [json_name = "heapUsedBytes"];</code>
     * @param value The heapUsedBytes to set.
     * @return This builder for chaining.
     */
    public Builder setHeapUsedBytes(long value) {

      heapUsedBytes_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 heap_used_bytes = 1 [json_name = "heapUsedBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHeapUsedBytes() {
      bitField0_ = (bitField0_ & ~0x00000001);
      heapUsedBytes_ = 0L;
      onChanged();
      return this;
    }

    private long heapMaxBytes_ ;
    /**
     * <code>int64 heap_max_bytes = 2 [json_name = "heapMaxBytes"];</code>
     * @return The heapMaxBytes.
     */
    @java.lang.Override
    public long getHeapMaxBytes() {
      return heapMaxBytes_;
    }
    /**
     * <code>int64 heap_max_bytes = 2 [json_name = "heapMaxBytes"];</code>
     * @param value The heapMaxBytes to set.
     * @return This builder for chaining.
     */
    public Builder setHeapMaxBytes(long value) {

      heapMaxBytes_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 heap_max_bytes = 2 [json_name = "heapMaxBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHeapMaxBytes() {
      bitField0_ = (bitField0_ & ~0x00000002);
      heapMaxBytes_ = 0L;
      onChanged();
      return this;
    }

    private long nonHeapUsedBytes_ ;
    /**
     * <code>int64 non_heap_used_bytes = 3 [json_name = "nonHeapUsedBytes"];</code>
     * @return The nonHeapUsedBytes.
     */
    @java.lang.Override
    public long getNonHeapUsedBytes() {
      return nonHeapUsedBytes_;
    }
    /**
     * <code>int64 non_heap_used_bytes = 3 [json_name = "nonHeapUsedBytes"];</code>
     * @param value The nonHeapUsedBytes to set.
     * @return This builder for chaining.
     */
    public Builder setNonHeapUsedBytes(long value) {

      nonHeapUsedBytes_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 non_heap_used_bytes = 3 [json_name = "nonHeapUsedBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNonHeapUsedBytes() {
      bitField0_ = (bitField0_ & ~0x00000004);
      nonHeapUsedBytes_ = 0L;
      onChanged();
      return this;
    }

    private long gcCount_ ;
    /**
     * <code>int64 gc_count = 4 [json_name = "gcCount"];</code>
     * @return The gcCount.
     */
    @java.lang.Override
    public long getGcCount() {
      return gcCount_;
    }
    /**
     * <code>int64 gc_count = 4 [json_name = "gcCount"];</code>
     * @param value The gcCount to set.
     * @return This builder for chaining.
     */
    public Builder setGcCount(long value) {

      gcCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 gc_count = 4 [json_name = "gcCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGcCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      gcCount_ = 0L;
      onChanged();
      return this;
    }

    private long gcTimeMillis_ ;
    /**
     * <code>int64 gc_time_millis = 5 [json_name = "gcTimeMillis"];</code>
     * @return The gcTimeMillis.
     */
    @java.lang.Override
    public long getGcTimeMillis() {
      return gcTimeMillis_;
    }
    /**
     * <code>int64 gc_time_millis = 5 [json_name = "gcTimeMillis"];</code>
     * @param value The gcTimeMillis to set.
     * @return This builder for chaining.
     */
    public Builder setGcTimeMillis(long value) {

      gcTimeMillis_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 gc_time_millis = 5 [json_name = "gcTimeMillis"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGcTimeMillis() {
      bitField0_ = (bitField0_ & ~0x00000010);
      gcTimeMillis_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.opensearch.protobufs.services.JvmMetrics)
  }

  // @@protoc_insertion_point(class_scope:org.opensearch.protobufs.services.JvmMetrics)
  private static final org.opensearch.protobufs.services.JvmMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opensearch.protobufs.services.JvmMetrics();
  }

  public static org.opensearch.protobufs.services.JvmMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JvmMetrics>
      PARSER = new com.google.protobuf.AbstractParser<JvmMetrics>() {
    @java.lang.Override
    public JvmMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JvmMetrics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JvmMetrics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opensearch.protobufs.services.JvmMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

