// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

/**
 * Protobuf enum {@code org.opensearch.protobufs.services.MetricCategory}
 */
public enum MetricCategory
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>THREAD_POOL = 0;</code>
   */
  THREAD_POOL(0),
  /**
   * <code>CIRCUIT_BREAKER = 1;</code>
   */
  CIRCUIT_BREAKER(1),
  /**
   * <code>INDEXING_PRESSURE = 2;</code>
   */
  INDEXING_PRESSURE(2),
  /**
   * <code>SEARCH_BACKPRESSURE = 3;</code>
   */
  SEARCH_BACKPRESSURE(3),
  /**
   * <code>JVM = 4;</code>
   */
  JVM(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>THREAD_POOL = 0;</code>
   */
  public static final int THREAD_POOL_VALUE = 0;
  /**
   * <code>CIRCUIT_BREAKER = 1;</code>
   */
  public static final int CIRCUIT_BREAKER_VALUE = 1;
  /**
   * <code>INDEXING_PRESSURE = 2;</code>
   */
  public static final int INDEXING_PRESSURE_VALUE = 2;
  /**
   * <code>SEARCH_BACKPRESSURE = 3;</code>
   */
  public static final int SEARCH_BACKPRESSURE_VALUE = 3;
  /**
   * <code>JVM = 4;</code>
   */
  public static final int JVM_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MetricCategory valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MetricCategory forNumber(int value) {
    switch (value) {
      case 0: return THREAD_POOL;
      case 1: return CIRCUIT_BREAKER;
      case 2: return INDEXING_PRESSURE;
      case 3: return SEARCH_BACKPRESSURE;
      case 4: return JVM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MetricCategory>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MetricCategory> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MetricCategory>() {
          public MetricCategory findValueByNumber(int number) {
            return MetricCategory.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.opensearch.protobufs.services.MetricsServiceProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final MetricCategory[] VALUES = values();

  public static MetricCategory valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MetricCategory(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.opensearch.protobufs.services.MetricCategory)
}

