// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

public final class MetricsServiceProto {
  private MetricsServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opensearch_protobufs_services_StreamMetricsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opensearch_protobufs_services_StreamMetricsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opensearch_protobufs_services_NodeMetricsSnapshot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opensearch_protobufs_services_NodeMetricsSnapshot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opensearch_protobufs_services_ThreadPoolMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opensearch_protobufs_services_ThreadPoolMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opensearch_protobufs_services_ThreadPoolStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opensearch_protobufs_services_ThreadPoolStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opensearch_protobufs_services_CircuitBreakerMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opensearch_protobufs_services_CircuitBreakerMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opensearch_protobufs_services_CircuitBreakerStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opensearch_protobufs_services_CircuitBreakerStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opensearch_protobufs_services_JvmMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opensearch_protobufs_services_JvmMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opensearch_protobufs_services_IndexingPressureMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opensearch_protobufs_services_IndexingPressureMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opensearch_protobufs_services_SearchBackpressureMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opensearch_protobufs_services_SearchBackpressureMetrics_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%protos/services/metrics_service.proto\022" +
      "!org.opensearch.protobufs.services\"\336\001\n\024S" +
      "treamMetricsRequest\022Q\n\ncategories\030\001 \003(\0162" +
      "1.org.opensearch.protobufs.services.Metr" +
      "icCategoryR\ncategories\022)\n\020interval_secon" +
      "ds\030\002 \001(\005R\017intervalSeconds\022\035\n\ndelta_mode\030" +
      "\003 \001(\010R\tdeltaMode\022)\n\020change_threshold\030\004 \001" +
      "(\002R\017changeThreshold\"\237\005\n\023NodeMetricsSnaps" +
      "hot\022)\n\020timestamp_millis\030\001 \001(\003R\017timestamp" +
      "Millis\022\027\n\007node_id\030\002 \001(\tR\006nodeId\022Z\n\013threa" +
      "d_pool\030\003 \001(\01324.org.opensearch.protobufs." +
      "services.ThreadPoolMetricsH\000R\nthreadPool" +
      "\210\001\001\022f\n\017circuit_breaker\030\004 \001(\01328.org.opens" +
      "earch.protobufs.services.CircuitBreakerM" +
      "etricsH\001R\016circuitBreaker\210\001\001\022l\n\021indexing_" +
      "pressure\030\005 \001(\0132:.org.opensearch.protobuf" +
      "s.services.IndexingPressureMetricsH\002R\020in" +
      "dexingPressure\210\001\001\022r\n\023search_backpressure" +
      "\030\006 \001(\0132<.org.opensearch.protobufs.servic" +
      "es.SearchBackpressureMetricsH\003R\022searchBa" +
      "ckpressure\210\001\001\022D\n\003jvm\030\007 \001(\0132-.org.opensea" +
      "rch.protobufs.services.JvmMetricsH\004R\003jvm" +
      "\210\001\001B\016\n\014_thread_poolB\022\n\020_circuit_breakerB" +
      "\024\n\022_indexing_pressureB\026\n\024_search_backpre" +
      "ssureB\006\n\004_jvm\"]\n\021ThreadPoolMetrics\022H\n\005po" +
      "ols\030\001 \003(\01322.org.opensearch.protobufs.ser" +
      "vices.ThreadPoolStatsR\005pools\"\351\001\n\017ThreadP" +
      "oolStats\022\022\n\004name\030\001 \001(\tR\004name\022\030\n\007threads\030" +
      "\002 \001(\005R\007threads\022\024\n\005queue\030\003 \001(\005R\005queue\022\026\n\006" +
      "active\030\004 \001(\005R\006active\022\032\n\010rejected\030\005 \001(\003R\010" +
      "rejected\022\030\n\007largest\030\006 \001(\005R\007largest\022\034\n\tco" +
      "mpleted\030\007 \001(\003R\tcompleted\022&\n\017wait_time_na" +
      "nos\030\010 \001(\003R\rwaitTimeNanos\"k\n\025CircuitBreak" +
      "erMetrics\022R\n\010breakers\030\001 \003(\01326.org.opense" +
      "arch.protobufs.services.CircuitBreakerSt" +
      "atsR\010breakers\"\223\001\n\023CircuitBreakerStats\022\022\n" +
      "\004name\030\001 \001(\tR\004name\022\024\n\005limit\030\002 \001(\003R\005limit\022" +
      "\034\n\testimated\030\003 \001(\003R\testimated\022\032\n\010overhea" +
      "d\030\004 \001(\001R\010overhead\022\030\n\007tripped\030\005 \001(\003R\007trip" +
      "ped\"\312\001\n\nJvmMetrics\022&\n\017heap_used_bytes\030\001 " +
      "\001(\003R\rheapUsedBytes\022$\n\016heap_max_bytes\030\002 \001" +
      "(\003R\014heapMaxBytes\022-\n\023non_heap_used_bytes\030" +
      "\003 \001(\003R\020nonHeapUsedBytes\022\031\n\010gc_count\030\004 \001(" +
      "\003R\007gcCount\022$\n\016gc_time_millis\030\005 \001(\003R\014gcTi" +
      "meMillis\"\216\003\n\027IndexingPressureMetrics\022<\n\032" +
      "current_coordinating_bytes\030\001 \001(\003R\030curren" +
      "tCoordinatingBytes\0222\n\025current_primary_by" +
      "tes\030\002 \001(\003R\023currentPrimaryBytes\0222\n\025curren" +
      "t_replica_bytes\030\003 \001(\003R\023currentReplicaByt" +
      "es\022>\n\033total_coordinating_rejected\030\004 \001(\003R" +
      "\031totalCoordinatingRejected\0224\n\026total_prim" +
      "ary_rejected\030\005 \001(\003R\024totalPrimaryRejected" +
      "\0224\n\026total_replica_rejected\030\006 \001(\003R\024totalR" +
      "eplicaRejected\022!\n\014memory_limit\030\007 \001(\003R\013me" +
      "moryLimit\"\322\001\n\031SearchBackpressureMetrics\022" +
      "*\n\021search_task_count\030\001 \001(\003R\017searchTaskCo" +
      "unt\0225\n\027search_shard_task_count\030\002 \001(\003R\024se" +
      "archShardTaskCount\022-\n\022cancellation_count" +
      "\030\003 \001(\003R\021cancellationCount\022#\n\rlimited_cou" +
      "nt\030\004 \001(\003R\014limitedCount*o\n\016MetricCategory" +
      "\022\017\n\013THREAD_POOL\020\000\022\023\n\017CIRCUIT_BREAKER\020\001\022\025" +
      "\n\021INDEXING_PRESSURE\020\002\022\027\n\023SEARCH_BACKPRES" +
      "SURE\020\003\022\007\n\003JVM\020\0042\233\001\n\016MetricsService\022\210\001\n\021S" +
      "treamNodeMetrics\0227.org.opensearch.protob" +
      "ufs.services.StreamMetricsRequest\0326.org." +
      "opensearch.protobufs.services.NodeMetric" +
      "sSnapshot\"\0000\001Bz\n!org.opensearch.protobuf" +
      "s.servicesB\023MetricsServiceProtoP\001Z>githu" +
      "b.com/opensearch-project/opensearch-prot" +
      "obufs/go/servicesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_opensearch_protobufs_services_StreamMetricsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_opensearch_protobufs_services_StreamMetricsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opensearch_protobufs_services_StreamMetricsRequest_descriptor,
        new java.lang.String[] { "Categories", "IntervalSeconds", "DeltaMode", "ChangeThreshold", });
    internal_static_org_opensearch_protobufs_services_NodeMetricsSnapshot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_opensearch_protobufs_services_NodeMetricsSnapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opensearch_protobufs_services_NodeMetricsSnapshot_descriptor,
        new java.lang.String[] { "TimestampMillis", "NodeId", "ThreadPool", "CircuitBreaker", "IndexingPressure", "SearchBackpressure", "Jvm", });
    internal_static_org_opensearch_protobufs_services_ThreadPoolMetrics_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_opensearch_protobufs_services_ThreadPoolMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opensearch_protobufs_services_ThreadPoolMetrics_descriptor,
        new java.lang.String[] { "Pools", });
    internal_static_org_opensearch_protobufs_services_ThreadPoolStats_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_opensearch_protobufs_services_ThreadPoolStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opensearch_protobufs_services_ThreadPoolStats_descriptor,
        new java.lang.String[] { "Name", "Threads", "Queue", "Active", "Rejected", "Largest", "Completed", "WaitTimeNanos", });
    internal_static_org_opensearch_protobufs_services_CircuitBreakerMetrics_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_opensearch_protobufs_services_CircuitBreakerMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opensearch_protobufs_services_CircuitBreakerMetrics_descriptor,
        new java.lang.String[] { "Breakers", });
    internal_static_org_opensearch_protobufs_services_CircuitBreakerStats_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_opensearch_protobufs_services_CircuitBreakerStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opensearch_protobufs_services_CircuitBreakerStats_descriptor,
        new java.lang.String[] { "Name", "Limit", "Estimated", "Overhead", "Tripped", });
    internal_static_org_opensearch_protobufs_services_JvmMetrics_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_opensearch_protobufs_services_JvmMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opensearch_protobufs_services_JvmMetrics_descriptor,
        new java.lang.String[] { "HeapUsedBytes", "HeapMaxBytes", "NonHeapUsedBytes", "GcCount", "GcTimeMillis", });
    internal_static_org_opensearch_protobufs_services_IndexingPressureMetrics_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_opensearch_protobufs_services_IndexingPressureMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opensearch_protobufs_services_IndexingPressureMetrics_descriptor,
        new java.lang.String[] { "CurrentCoordinatingBytes", "CurrentPrimaryBytes", "CurrentReplicaBytes", "TotalCoordinatingRejected", "TotalPrimaryRejected", "TotalReplicaRejected", "MemoryLimit", });
    internal_static_org_opensearch_protobufs_services_SearchBackpressureMetrics_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_org_opensearch_protobufs_services_SearchBackpressureMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opensearch_protobufs_services_SearchBackpressureMetrics_descriptor,
        new java.lang.String[] { "SearchTaskCount", "SearchShardTaskCount", "CancellationCount", "LimitedCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
