// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

/**
 * Protobuf type {@code org.opensearch.protobufs.services.NodeMetricsSnapshot}
 */
public final class NodeMetricsSnapshot extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.opensearch.protobufs.services.NodeMetricsSnapshot)
    NodeMetricsSnapshotOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NodeMetricsSnapshot.newBuilder() to construct.
  private NodeMetricsSnapshot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NodeMetricsSnapshot() {
    nodeId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NodeMetricsSnapshot();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_NodeMetricsSnapshot_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_NodeMetricsSnapshot_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opensearch.protobufs.services.NodeMetricsSnapshot.class, org.opensearch.protobufs.services.NodeMetricsSnapshot.Builder.class);
  }

  private int bitField0_;
  public static final int TIMESTAMP_MILLIS_FIELD_NUMBER = 1;
  private long timestampMillis_ = 0L;
  /**
   * <code>int64 timestamp_millis = 1 [json_name = "timestampMillis"];</code>
   * @return The timestampMillis.
   */
  @java.lang.Override
  public long getTimestampMillis() {
    return timestampMillis_;
  }

  public static final int NODE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nodeId_ = "";
  /**
   * <code>string node_id = 2 [json_name = "nodeId"];</code>
   * @return The nodeId.
   */
  @java.lang.Override
  public java.lang.String getNodeId() {
    java.lang.Object ref = nodeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeId_ = s;
      return s;
    }
  }
  /**
   * <code>string node_id = 2 [json_name = "nodeId"];</code>
   * @return The bytes for nodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeIdBytes() {
    java.lang.Object ref = nodeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int THREAD_POOL_FIELD_NUMBER = 3;
  private org.opensearch.protobufs.services.ThreadPoolMetrics threadPool_;
  /**
   * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
   * @return Whether the threadPool field is set.
   */
  @java.lang.Override
  public boolean hasThreadPool() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
   * @return The threadPool.
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.ThreadPoolMetrics getThreadPool() {
    return threadPool_ == null ? org.opensearch.protobufs.services.ThreadPoolMetrics.getDefaultInstance() : threadPool_;
  }
  /**
   * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.ThreadPoolMetricsOrBuilder getThreadPoolOrBuilder() {
    return threadPool_ == null ? org.opensearch.protobufs.services.ThreadPoolMetrics.getDefaultInstance() : threadPool_;
  }

  public static final int CIRCUIT_BREAKER_FIELD_NUMBER = 4;
  private org.opensearch.protobufs.services.CircuitBreakerMetrics circuitBreaker_;
  /**
   * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
   * @return Whether the circuitBreaker field is set.
   */
  @java.lang.Override
  public boolean hasCircuitBreaker() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
   * @return The circuitBreaker.
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.CircuitBreakerMetrics getCircuitBreaker() {
    return circuitBreaker_ == null ? org.opensearch.protobufs.services.CircuitBreakerMetrics.getDefaultInstance() : circuitBreaker_;
  }
  /**
   * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.CircuitBreakerMetricsOrBuilder getCircuitBreakerOrBuilder() {
    return circuitBreaker_ == null ? org.opensearch.protobufs.services.CircuitBreakerMetrics.getDefaultInstance() : circuitBreaker_;
  }

  public static final int INDEXING_PRESSURE_FIELD_NUMBER = 5;
  private org.opensearch.protobufs.services.IndexingPressureMetrics indexingPressure_;
  /**
   * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
   * @return Whether the indexingPressure field is set.
   */
  @java.lang.Override
  public boolean hasIndexingPressure() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
   * @return The indexingPressure.
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.IndexingPressureMetrics getIndexingPressure() {
    return indexingPressure_ == null ? org.opensearch.protobufs.services.IndexingPressureMetrics.getDefaultInstance() : indexingPressure_;
  }
  /**
   * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.IndexingPressureMetricsOrBuilder getIndexingPressureOrBuilder() {
    return indexingPressure_ == null ? org.opensearch.protobufs.services.IndexingPressureMetrics.getDefaultInstance() : indexingPressure_;
  }

  public static final int SEARCH_BACKPRESSURE_FIELD_NUMBER = 6;
  private org.opensearch.protobufs.services.SearchBackpressureMetrics searchBackpressure_;
  /**
   * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
   * @return Whether the searchBackpressure field is set.
   */
  @java.lang.Override
  public boolean hasSearchBackpressure() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
   * @return The searchBackpressure.
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.SearchBackpressureMetrics getSearchBackpressure() {
    return searchBackpressure_ == null ? org.opensearch.protobufs.services.SearchBackpressureMetrics.getDefaultInstance() : searchBackpressure_;
  }
  /**
   * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.SearchBackpressureMetricsOrBuilder getSearchBackpressureOrBuilder() {
    return searchBackpressure_ == null ? org.opensearch.protobufs.services.SearchBackpressureMetrics.getDefaultInstance() : searchBackpressure_;
  }

  public static final int JVM_FIELD_NUMBER = 7;
  private org.opensearch.protobufs.services.JvmMetrics jvm_;
  /**
   * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
   * @return Whether the jvm field is set.
   */
  @java.lang.Override
  public boolean hasJvm() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
   * @return The jvm.
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.JvmMetrics getJvm() {
    return jvm_ == null ? org.opensearch.protobufs.services.JvmMetrics.getDefaultInstance() : jvm_;
  }
  /**
   * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.JvmMetricsOrBuilder getJvmOrBuilder() {
    return jvm_ == null ? org.opensearch.protobufs.services.JvmMetrics.getDefaultInstance() : jvm_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestampMillis_ != 0L) {
      output.writeInt64(1, timestampMillis_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getThreadPool());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getCircuitBreaker());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(5, getIndexingPressure());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(6, getSearchBackpressure());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(7, getJvm());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestampMillis_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestampMillis_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getThreadPool());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCircuitBreaker());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getIndexingPressure());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getSearchBackpressure());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getJvm());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opensearch.protobufs.services.NodeMetricsSnapshot)) {
      return super.equals(obj);
    }
    org.opensearch.protobufs.services.NodeMetricsSnapshot other = (org.opensearch.protobufs.services.NodeMetricsSnapshot) obj;

    if (getTimestampMillis()
        != other.getTimestampMillis()) return false;
    if (!getNodeId()
        .equals(other.getNodeId())) return false;
    if (hasThreadPool() != other.hasThreadPool()) return false;
    if (hasThreadPool()) {
      if (!getThreadPool()
          .equals(other.getThreadPool())) return false;
    }
    if (hasCircuitBreaker() != other.hasCircuitBreaker()) return false;
    if (hasCircuitBreaker()) {
      if (!getCircuitBreaker()
          .equals(other.getCircuitBreaker())) return false;
    }
    if (hasIndexingPressure() != other.hasIndexingPressure()) return false;
    if (hasIndexingPressure()) {
      if (!getIndexingPressure()
          .equals(other.getIndexingPressure())) return false;
    }
    if (hasSearchBackpressure() != other.hasSearchBackpressure()) return false;
    if (hasSearchBackpressure()) {
      if (!getSearchBackpressure()
          .equals(other.getSearchBackpressure())) return false;
    }
    if (hasJvm() != other.hasJvm()) return false;
    if (hasJvm()) {
      if (!getJvm()
          .equals(other.getJvm())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_MILLIS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestampMillis());
    hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeId().hashCode();
    if (hasThreadPool()) {
      hash = (37 * hash) + THREAD_POOL_FIELD_NUMBER;
      hash = (53 * hash) + getThreadPool().hashCode();
    }
    if (hasCircuitBreaker()) {
      hash = (37 * hash) + CIRCUIT_BREAKER_FIELD_NUMBER;
      hash = (53 * hash) + getCircuitBreaker().hashCode();
    }
    if (hasIndexingPressure()) {
      hash = (37 * hash) + INDEXING_PRESSURE_FIELD_NUMBER;
      hash = (53 * hash) + getIndexingPressure().hashCode();
    }
    if (hasSearchBackpressure()) {
      hash = (37 * hash) + SEARCH_BACKPRESSURE_FIELD_NUMBER;
      hash = (53 * hash) + getSearchBackpressure().hashCode();
    }
    if (hasJvm()) {
      hash = (37 * hash) + JVM_FIELD_NUMBER;
      hash = (53 * hash) + getJvm().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opensearch.protobufs.services.NodeMetricsSnapshot parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.NodeMetricsSnapshot parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.NodeMetricsSnapshot parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.NodeMetricsSnapshot parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.NodeMetricsSnapshot parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.NodeMetricsSnapshot parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.NodeMetricsSnapshot parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.NodeMetricsSnapshot parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.opensearch.protobufs.services.NodeMetricsSnapshot parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.opensearch.protobufs.services.NodeMetricsSnapshot parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.NodeMetricsSnapshot parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.NodeMetricsSnapshot parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opensearch.protobufs.services.NodeMetricsSnapshot prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.opensearch.protobufs.services.NodeMetricsSnapshot}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.opensearch.protobufs.services.NodeMetricsSnapshot)
      org.opensearch.protobufs.services.NodeMetricsSnapshotOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_NodeMetricsSnapshot_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_NodeMetricsSnapshot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opensearch.protobufs.services.NodeMetricsSnapshot.class, org.opensearch.protobufs.services.NodeMetricsSnapshot.Builder.class);
    }

    // Construct using org.opensearch.protobufs.services.NodeMetricsSnapshot.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getThreadPoolFieldBuilder();
        getCircuitBreakerFieldBuilder();
        getIndexingPressureFieldBuilder();
        getSearchBackpressureFieldBuilder();
        getJvmFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timestampMillis_ = 0L;
      nodeId_ = "";
      threadPool_ = null;
      if (threadPoolBuilder_ != null) {
        threadPoolBuilder_.dispose();
        threadPoolBuilder_ = null;
      }
      circuitBreaker_ = null;
      if (circuitBreakerBuilder_ != null) {
        circuitBreakerBuilder_.dispose();
        circuitBreakerBuilder_ = null;
      }
      indexingPressure_ = null;
      if (indexingPressureBuilder_ != null) {
        indexingPressureBuilder_.dispose();
        indexingPressureBuilder_ = null;
      }
      searchBackpressure_ = null;
      if (searchBackpressureBuilder_ != null) {
        searchBackpressureBuilder_.dispose();
        searchBackpressureBuilder_ = null;
      }
      jvm_ = null;
      if (jvmBuilder_ != null) {
        jvmBuilder_.dispose();
        jvmBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_NodeMetricsSnapshot_descriptor;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.NodeMetricsSnapshot getDefaultInstanceForType() {
      return org.opensearch.protobufs.services.NodeMetricsSnapshot.getDefaultInstance();
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.NodeMetricsSnapshot build() {
      org.opensearch.protobufs.services.NodeMetricsSnapshot result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.NodeMetricsSnapshot buildPartial() {
      org.opensearch.protobufs.services.NodeMetricsSnapshot result = new org.opensearch.protobufs.services.NodeMetricsSnapshot(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.opensearch.protobufs.services.NodeMetricsSnapshot result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timestampMillis_ = timestampMillis_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nodeId_ = nodeId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.threadPool_ = threadPoolBuilder_ == null
            ? threadPool_
            : threadPoolBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.circuitBreaker_ = circuitBreakerBuilder_ == null
            ? circuitBreaker_
            : circuitBreakerBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.indexingPressure_ = indexingPressureBuilder_ == null
            ? indexingPressure_
            : indexingPressureBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.searchBackpressure_ = searchBackpressureBuilder_ == null
            ? searchBackpressure_
            : searchBackpressureBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.jvm_ = jvmBuilder_ == null
            ? jvm_
            : jvmBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opensearch.protobufs.services.NodeMetricsSnapshot) {
        return mergeFrom((org.opensearch.protobufs.services.NodeMetricsSnapshot)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opensearch.protobufs.services.NodeMetricsSnapshot other) {
      if (other == org.opensearch.protobufs.services.NodeMetricsSnapshot.getDefaultInstance()) return this;
      if (other.getTimestampMillis() != 0L) {
        setTimestampMillis(other.getTimestampMillis());
      }
      if (!other.getNodeId().isEmpty()) {
        nodeId_ = other.nodeId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasThreadPool()) {
        mergeThreadPool(other.getThreadPool());
      }
      if (other.hasCircuitBreaker()) {
        mergeCircuitBreaker(other.getCircuitBreaker());
      }
      if (other.hasIndexingPressure()) {
        mergeIndexingPressure(other.getIndexingPressure());
      }
      if (other.hasSearchBackpressure()) {
        mergeSearchBackpressure(other.getSearchBackpressure());
      }
      if (other.hasJvm()) {
        mergeJvm(other.getJvm());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              timestampMillis_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              nodeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getThreadPoolFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getCircuitBreakerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getIndexingPressureFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getSearchBackpressureFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getJvmFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long timestampMillis_ ;
    /**
     * <code>int64 timestamp_millis = 1 [json_name = "timestampMillis"];</code>
     * @return The timestampMillis.
     */
    @java.lang.Override
    public long getTimestampMillis() {
      return timestampMillis_;
    }
    /**
     * <code>int64 timestamp_millis = 1 [json_name = "timestampMillis"];</code>
     * @param value The timestampMillis to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampMillis(long value) {

      timestampMillis_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp_millis = 1 [json_name = "timestampMillis"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampMillis() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestampMillis_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object nodeId_ = "";
    /**
     * <code>string node_id = 2 [json_name = "nodeId"];</code>
     * @return The nodeId.
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string node_id = 2 [json_name = "nodeId"];</code>
     * @return The bytes for nodeId.
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string node_id = 2 [json_name = "nodeId"];</code>
     * @param value The nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nodeId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string node_id = 2 [json_name = "nodeId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeId() {
      nodeId_ = getDefaultInstance().getNodeId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string node_id = 2 [json_name = "nodeId"];</code>
     * @param value The bytes for nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nodeId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private org.opensearch.protobufs.services.ThreadPoolMetrics threadPool_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.opensearch.protobufs.services.ThreadPoolMetrics, org.opensearch.protobufs.services.ThreadPoolMetrics.Builder, org.opensearch.protobufs.services.ThreadPoolMetricsOrBuilder> threadPoolBuilder_;
    /**
     * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
     * @return Whether the threadPool field is set.
     */
    public boolean hasThreadPool() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
     * @return The threadPool.
     */
    public org.opensearch.protobufs.services.ThreadPoolMetrics getThreadPool() {
      if (threadPoolBuilder_ == null) {
        return threadPool_ == null ? org.opensearch.protobufs.services.ThreadPoolMetrics.getDefaultInstance() : threadPool_;
      } else {
        return threadPoolBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
     */
    public Builder setThreadPool(org.opensearch.protobufs.services.ThreadPoolMetrics value) {
      if (threadPoolBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        threadPool_ = value;
      } else {
        threadPoolBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
     */
    public Builder setThreadPool(
        org.opensearch.protobufs.services.ThreadPoolMetrics.Builder builderForValue) {
      if (threadPoolBuilder_ == null) {
        threadPool_ = builderForValue.build();
      } else {
        threadPoolBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
     */
    public Builder mergeThreadPool(org.opensearch.protobufs.services.ThreadPoolMetrics value) {
      if (threadPoolBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          threadPool_ != null &&
          threadPool_ != org.opensearch.protobufs.services.ThreadPoolMetrics.getDefaultInstance()) {
          getThreadPoolBuilder().mergeFrom(value);
        } else {
          threadPool_ = value;
        }
      } else {
        threadPoolBuilder_.mergeFrom(value);
      }
      if (threadPool_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
     */
    public Builder clearThreadPool() {
      bitField0_ = (bitField0_ & ~0x00000004);
      threadPool_ = null;
      if (threadPoolBuilder_ != null) {
        threadPoolBuilder_.dispose();
        threadPoolBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
     */
    public org.opensearch.protobufs.services.ThreadPoolMetrics.Builder getThreadPoolBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getThreadPoolFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
     */
    public org.opensearch.protobufs.services.ThreadPoolMetricsOrBuilder getThreadPoolOrBuilder() {
      if (threadPoolBuilder_ != null) {
        return threadPoolBuilder_.getMessageOrBuilder();
      } else {
        return threadPool_ == null ?
            org.opensearch.protobufs.services.ThreadPoolMetrics.getDefaultInstance() : threadPool_;
      }
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.opensearch.protobufs.services.ThreadPoolMetrics, org.opensearch.protobufs.services.ThreadPoolMetrics.Builder, org.opensearch.protobufs.services.ThreadPoolMetricsOrBuilder> 
        getThreadPoolFieldBuilder() {
      if (threadPoolBuilder_ == null) {
        threadPoolBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.opensearch.protobufs.services.ThreadPoolMetrics, org.opensearch.protobufs.services.ThreadPoolMetrics.Builder, org.opensearch.protobufs.services.ThreadPoolMetricsOrBuilder>(
                getThreadPool(),
                getParentForChildren(),
                isClean());
        threadPool_ = null;
      }
      return threadPoolBuilder_;
    }

    private org.opensearch.protobufs.services.CircuitBreakerMetrics circuitBreaker_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.opensearch.protobufs.services.CircuitBreakerMetrics, org.opensearch.protobufs.services.CircuitBreakerMetrics.Builder, org.opensearch.protobufs.services.CircuitBreakerMetricsOrBuilder> circuitBreakerBuilder_;
    /**
     * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
     * @return Whether the circuitBreaker field is set.
     */
    public boolean hasCircuitBreaker() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
     * @return The circuitBreaker.
     */
    public org.opensearch.protobufs.services.CircuitBreakerMetrics getCircuitBreaker() {
      if (circuitBreakerBuilder_ == null) {
        return circuitBreaker_ == null ? org.opensearch.protobufs.services.CircuitBreakerMetrics.getDefaultInstance() : circuitBreaker_;
      } else {
        return circuitBreakerBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
     */
    public Builder setCircuitBreaker(org.opensearch.protobufs.services.CircuitBreakerMetrics value) {
      if (circuitBreakerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        circuitBreaker_ = value;
      } else {
        circuitBreakerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
     */
    public Builder setCircuitBreaker(
        org.opensearch.protobufs.services.CircuitBreakerMetrics.Builder builderForValue) {
      if (circuitBreakerBuilder_ == null) {
        circuitBreaker_ = builderForValue.build();
      } else {
        circuitBreakerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
     */
    public Builder mergeCircuitBreaker(org.opensearch.protobufs.services.CircuitBreakerMetrics value) {
      if (circuitBreakerBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          circuitBreaker_ != null &&
          circuitBreaker_ != org.opensearch.protobufs.services.CircuitBreakerMetrics.getDefaultInstance()) {
          getCircuitBreakerBuilder().mergeFrom(value);
        } else {
          circuitBreaker_ = value;
        }
      } else {
        circuitBreakerBuilder_.mergeFrom(value);
      }
      if (circuitBreaker_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
     */
    public Builder clearCircuitBreaker() {
      bitField0_ = (bitField0_ & ~0x00000008);
      circuitBreaker_ = null;
      if (circuitBreakerBuilder_ != null) {
        circuitBreakerBuilder_.dispose();
        circuitBreakerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
     */
    public org.opensearch.protobufs.services.CircuitBreakerMetrics.Builder getCircuitBreakerBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getCircuitBreakerFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
     */
    public org.opensearch.protobufs.services.CircuitBreakerMetricsOrBuilder getCircuitBreakerOrBuilder() {
      if (circuitBreakerBuilder_ != null) {
        return circuitBreakerBuilder_.getMessageOrBuilder();
      } else {
        return circuitBreaker_ == null ?
            org.opensearch.protobufs.services.CircuitBreakerMetrics.getDefaultInstance() : circuitBreaker_;
      }
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.opensearch.protobufs.services.CircuitBreakerMetrics, org.opensearch.protobufs.services.CircuitBreakerMetrics.Builder, org.opensearch.protobufs.services.CircuitBreakerMetricsOrBuilder> 
        getCircuitBreakerFieldBuilder() {
      if (circuitBreakerBuilder_ == null) {
        circuitBreakerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.opensearch.protobufs.services.CircuitBreakerMetrics, org.opensearch.protobufs.services.CircuitBreakerMetrics.Builder, org.opensearch.protobufs.services.CircuitBreakerMetricsOrBuilder>(
                getCircuitBreaker(),
                getParentForChildren(),
                isClean());
        circuitBreaker_ = null;
      }
      return circuitBreakerBuilder_;
    }

    private org.opensearch.protobufs.services.IndexingPressureMetrics indexingPressure_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.opensearch.protobufs.services.IndexingPressureMetrics, org.opensearch.protobufs.services.IndexingPressureMetrics.Builder, org.opensearch.protobufs.services.IndexingPressureMetricsOrBuilder> indexingPressureBuilder_;
    /**
     * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
     * @return Whether the indexingPressure field is set.
     */
    public boolean hasIndexingPressure() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
     * @return The indexingPressure.
     */
    public org.opensearch.protobufs.services.IndexingPressureMetrics getIndexingPressure() {
      if (indexingPressureBuilder_ == null) {
        return indexingPressure_ == null ? org.opensearch.protobufs.services.IndexingPressureMetrics.getDefaultInstance() : indexingPressure_;
      } else {
        return indexingPressureBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
     */
    public Builder setIndexingPressure(org.opensearch.protobufs.services.IndexingPressureMetrics value) {
      if (indexingPressureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        indexingPressure_ = value;
      } else {
        indexingPressureBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
     */
    public Builder setIndexingPressure(
        org.opensearch.protobufs.services.IndexingPressureMetrics.Builder builderForValue) {
      if (indexingPressureBuilder_ == null) {
        indexingPressure_ = builderForValue.build();
      } else {
        indexingPressureBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
     */
    public Builder mergeIndexingPressure(org.opensearch.protobufs.services.IndexingPressureMetrics value) {
      if (indexingPressureBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          indexingPressure_ != null &&
          indexingPressure_ != org.opensearch.protobufs.services.IndexingPressureMetrics.getDefaultInstance()) {
          getIndexingPressureBuilder().mergeFrom(value);
        } else {
          indexingPressure_ = value;
        }
      } else {
        indexingPressureBuilder_.mergeFrom(value);
      }
      if (indexingPressure_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
     */
    public Builder clearIndexingPressure() {
      bitField0_ = (bitField0_ & ~0x00000010);
      indexingPressure_ = null;
      if (indexingPressureBuilder_ != null) {
        indexingPressureBuilder_.dispose();
        indexingPressureBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
     */
    public org.opensearch.protobufs.services.IndexingPressureMetrics.Builder getIndexingPressureBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getIndexingPressureFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
     */
    public org.opensearch.protobufs.services.IndexingPressureMetricsOrBuilder getIndexingPressureOrBuilder() {
      if (indexingPressureBuilder_ != null) {
        return indexingPressureBuilder_.getMessageOrBuilder();
      } else {
        return indexingPressure_ == null ?
            org.opensearch.protobufs.services.IndexingPressureMetrics.getDefaultInstance() : indexingPressure_;
      }
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.opensearch.protobufs.services.IndexingPressureMetrics, org.opensearch.protobufs.services.IndexingPressureMetrics.Builder, org.opensearch.protobufs.services.IndexingPressureMetricsOrBuilder> 
        getIndexingPressureFieldBuilder() {
      if (indexingPressureBuilder_ == null) {
        indexingPressureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.opensearch.protobufs.services.IndexingPressureMetrics, org.opensearch.protobufs.services.IndexingPressureMetrics.Builder, org.opensearch.protobufs.services.IndexingPressureMetricsOrBuilder>(
                getIndexingPressure(),
                getParentForChildren(),
                isClean());
        indexingPressure_ = null;
      }
      return indexingPressureBuilder_;
    }

    private org.opensearch.protobufs.services.SearchBackpressureMetrics searchBackpressure_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.opensearch.protobufs.services.SearchBackpressureMetrics, org.opensearch.protobufs.services.SearchBackpressureMetrics.Builder, org.opensearch.protobufs.services.SearchBackpressureMetricsOrBuilder> searchBackpressureBuilder_;
    /**
     * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
     * @return Whether the searchBackpressure field is set.
     */
    public boolean hasSearchBackpressure() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
     * @return The searchBackpressure.
     */
    public org.opensearch.protobufs.services.SearchBackpressureMetrics getSearchBackpressure() {
      if (searchBackpressureBuilder_ == null) {
        return searchBackpressure_ == null ? org.opensearch.protobufs.services.SearchBackpressureMetrics.getDefaultInstance() : searchBackpressure_;
      } else {
        return searchBackpressureBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
     */
    public Builder setSearchBackpressure(org.opensearch.protobufs.services.SearchBackpressureMetrics value) {
      if (searchBackpressureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        searchBackpressure_ = value;
      } else {
        searchBackpressureBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
     */
    public Builder setSearchBackpressure(
        org.opensearch.protobufs.services.SearchBackpressureMetrics.Builder builderForValue) {
      if (searchBackpressureBuilder_ == null) {
        searchBackpressure_ = builderForValue.build();
      } else {
        searchBackpressureBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
     */
    public Builder mergeSearchBackpressure(org.opensearch.protobufs.services.SearchBackpressureMetrics value) {
      if (searchBackpressureBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          searchBackpressure_ != null &&
          searchBackpressure_ != org.opensearch.protobufs.services.SearchBackpressureMetrics.getDefaultInstance()) {
          getSearchBackpressureBuilder().mergeFrom(value);
        } else {
          searchBackpressure_ = value;
        }
      } else {
        searchBackpressureBuilder_.mergeFrom(value);
      }
      if (searchBackpressure_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
     */
    public Builder clearSearchBackpressure() {
      bitField0_ = (bitField0_ & ~0x00000020);
      searchBackpressure_ = null;
      if (searchBackpressureBuilder_ != null) {
        searchBackpressureBuilder_.dispose();
        searchBackpressureBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
     */
    public org.opensearch.protobufs.services.SearchBackpressureMetrics.Builder getSearchBackpressureBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getSearchBackpressureFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
     */
    public org.opensearch.protobufs.services.SearchBackpressureMetricsOrBuilder getSearchBackpressureOrBuilder() {
      if (searchBackpressureBuilder_ != null) {
        return searchBackpressureBuilder_.getMessageOrBuilder();
      } else {
        return searchBackpressure_ == null ?
            org.opensearch.protobufs.services.SearchBackpressureMetrics.getDefaultInstance() : searchBackpressure_;
      }
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.opensearch.protobufs.services.SearchBackpressureMetrics, org.opensearch.protobufs.services.SearchBackpressureMetrics.Builder, org.opensearch.protobufs.services.SearchBackpressureMetricsOrBuilder> 
        getSearchBackpressureFieldBuilder() {
      if (searchBackpressureBuilder_ == null) {
        searchBackpressureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.opensearch.protobufs.services.SearchBackpressureMetrics, org.opensearch.protobufs.services.SearchBackpressureMetrics.Builder, org.opensearch.protobufs.services.SearchBackpressureMetricsOrBuilder>(
                getSearchBackpressure(),
                getParentForChildren(),
                isClean());
        searchBackpressure_ = null;
      }
      return searchBackpressureBuilder_;
    }

    private org.opensearch.protobufs.services.JvmMetrics jvm_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.opensearch.protobufs.services.JvmMetrics, org.opensearch.protobufs.services.JvmMetrics.Builder, org.opensearch.protobufs.services.JvmMetricsOrBuilder> jvmBuilder_;
    /**
     * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
     * @return Whether the jvm field is set.
     */
    public boolean hasJvm() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
     * @return The jvm.
     */
    public org.opensearch.protobufs.services.JvmMetrics getJvm() {
      if (jvmBuilder_ == null) {
        return jvm_ == null ? org.opensearch.protobufs.services.JvmMetrics.getDefaultInstance() : jvm_;
      } else {
        return jvmBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
     */
    public Builder setJvm(org.opensearch.protobufs.services.JvmMetrics value) {
      if (jvmBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        jvm_ = value;
      } else {
        jvmBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
     */
    public Builder setJvm(
        org.opensearch.protobufs.services.JvmMetrics.Builder builderForValue) {
      if (jvmBuilder_ == null) {
        jvm_ = builderForValue.build();
      } else {
        jvmBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
     */
    public Builder mergeJvm(org.opensearch.protobufs.services.JvmMetrics value) {
      if (jvmBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          jvm_ != null &&
          jvm_ != org.opensearch.protobufs.services.JvmMetrics.getDefaultInstance()) {
          getJvmBuilder().mergeFrom(value);
        } else {
          jvm_ = value;
        }
      } else {
        jvmBuilder_.mergeFrom(value);
      }
      if (jvm_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
     */
    public Builder clearJvm() {
      bitField0_ = (bitField0_ & ~0x00000040);
      jvm_ = null;
      if (jvmBuilder_ != null) {
        jvmBuilder_.dispose();
        jvmBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
     */
    public org.opensearch.protobufs.services.JvmMetrics.Builder getJvmBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getJvmFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
     */
    public org.opensearch.protobufs.services.JvmMetricsOrBuilder getJvmOrBuilder() {
      if (jvmBuilder_ != null) {
        return jvmBuilder_.getMessageOrBuilder();
      } else {
        return jvm_ == null ?
            org.opensearch.protobufs.services.JvmMetrics.getDefaultInstance() : jvm_;
      }
    }
    /**
     * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.opensearch.protobufs.services.JvmMetrics, org.opensearch.protobufs.services.JvmMetrics.Builder, org.opensearch.protobufs.services.JvmMetricsOrBuilder> 
        getJvmFieldBuilder() {
      if (jvmBuilder_ == null) {
        jvmBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.opensearch.protobufs.services.JvmMetrics, org.opensearch.protobufs.services.JvmMetrics.Builder, org.opensearch.protobufs.services.JvmMetricsOrBuilder>(
                getJvm(),
                getParentForChildren(),
                isClean());
        jvm_ = null;
      }
      return jvmBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.opensearch.protobufs.services.NodeMetricsSnapshot)
  }

  // @@protoc_insertion_point(class_scope:org.opensearch.protobufs.services.NodeMetricsSnapshot)
  private static final org.opensearch.protobufs.services.NodeMetricsSnapshot DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opensearch.protobufs.services.NodeMetricsSnapshot();
  }

  public static org.opensearch.protobufs.services.NodeMetricsSnapshot getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NodeMetricsSnapshot>
      PARSER = new com.google.protobuf.AbstractParser<NodeMetricsSnapshot>() {
    @java.lang.Override
    public NodeMetricsSnapshot parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NodeMetricsSnapshot> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NodeMetricsSnapshot> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opensearch.protobufs.services.NodeMetricsSnapshot getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

