// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

public interface NodeMetricsSnapshotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opensearch.protobufs.services.NodeMetricsSnapshot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp_millis = 1 [json_name = "timestampMillis"];</code>
   * @return The timestampMillis.
   */
  long getTimestampMillis();

  /**
   * <code>string node_id = 2 [json_name = "nodeId"];</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 2 [json_name = "nodeId"];</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
   * @return Whether the threadPool field is set.
   */
  boolean hasThreadPool();
  /**
   * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
   * @return The threadPool.
   */
  org.opensearch.protobufs.services.ThreadPoolMetrics getThreadPool();
  /**
   * <code>optional .org.opensearch.protobufs.services.ThreadPoolMetrics thread_pool = 3 [json_name = "threadPool"];</code>
   */
  org.opensearch.protobufs.services.ThreadPoolMetricsOrBuilder getThreadPoolOrBuilder();

  /**
   * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
   * @return Whether the circuitBreaker field is set.
   */
  boolean hasCircuitBreaker();
  /**
   * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
   * @return The circuitBreaker.
   */
  org.opensearch.protobufs.services.CircuitBreakerMetrics getCircuitBreaker();
  /**
   * <code>optional .org.opensearch.protobufs.services.CircuitBreakerMetrics circuit_breaker = 4 [json_name = "circuitBreaker"];</code>
   */
  org.opensearch.protobufs.services.CircuitBreakerMetricsOrBuilder getCircuitBreakerOrBuilder();

  /**
   * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
   * @return Whether the indexingPressure field is set.
   */
  boolean hasIndexingPressure();
  /**
   * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
   * @return The indexingPressure.
   */
  org.opensearch.protobufs.services.IndexingPressureMetrics getIndexingPressure();
  /**
   * <code>optional .org.opensearch.protobufs.services.IndexingPressureMetrics indexing_pressure = 5 [json_name = "indexingPressure"];</code>
   */
  org.opensearch.protobufs.services.IndexingPressureMetricsOrBuilder getIndexingPressureOrBuilder();

  /**
   * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
   * @return Whether the searchBackpressure field is set.
   */
  boolean hasSearchBackpressure();
  /**
   * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
   * @return The searchBackpressure.
   */
  org.opensearch.protobufs.services.SearchBackpressureMetrics getSearchBackpressure();
  /**
   * <code>optional .org.opensearch.protobufs.services.SearchBackpressureMetrics search_backpressure = 6 [json_name = "searchBackpressure"];</code>
   */
  org.opensearch.protobufs.services.SearchBackpressureMetricsOrBuilder getSearchBackpressureOrBuilder();

  /**
   * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
   * @return Whether the jvm field is set.
   */
  boolean hasJvm();
  /**
   * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
   * @return The jvm.
   */
  org.opensearch.protobufs.services.JvmMetrics getJvm();
  /**
   * <code>optional .org.opensearch.protobufs.services.JvmMetrics jvm = 7 [json_name = "jvm"];</code>
   */
  org.opensearch.protobufs.services.JvmMetricsOrBuilder getJvmOrBuilder();
}
