// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

/**
 * Protobuf type {@code org.opensearch.protobufs.services.SearchBackpressureMetrics}
 */
public final class SearchBackpressureMetrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.opensearch.protobufs.services.SearchBackpressureMetrics)
    SearchBackpressureMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchBackpressureMetrics.newBuilder() to construct.
  private SearchBackpressureMetrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchBackpressureMetrics() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchBackpressureMetrics();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_SearchBackpressureMetrics_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_SearchBackpressureMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opensearch.protobufs.services.SearchBackpressureMetrics.class, org.opensearch.protobufs.services.SearchBackpressureMetrics.Builder.class);
  }

  public static final int SEARCH_TASK_COUNT_FIELD_NUMBER = 1;
  private long searchTaskCount_ = 0L;
  /**
   * <code>int64 search_task_count = 1 [json_name = "searchTaskCount"];</code>
   * @return The searchTaskCount.
   */
  @java.lang.Override
  public long getSearchTaskCount() {
    return searchTaskCount_;
  }

  public static final int SEARCH_SHARD_TASK_COUNT_FIELD_NUMBER = 2;
  private long searchShardTaskCount_ = 0L;
  /**
   * <code>int64 search_shard_task_count = 2 [json_name = "searchShardTaskCount"];</code>
   * @return The searchShardTaskCount.
   */
  @java.lang.Override
  public long getSearchShardTaskCount() {
    return searchShardTaskCount_;
  }

  public static final int CANCELLATION_COUNT_FIELD_NUMBER = 3;
  private long cancellationCount_ = 0L;
  /**
   * <code>int64 cancellation_count = 3 [json_name = "cancellationCount"];</code>
   * @return The cancellationCount.
   */
  @java.lang.Override
  public long getCancellationCount() {
    return cancellationCount_;
  }

  public static final int LIMITED_COUNT_FIELD_NUMBER = 4;
  private long limitedCount_ = 0L;
  /**
   * <code>int64 limited_count = 4 [json_name = "limitedCount"];</code>
   * @return The limitedCount.
   */
  @java.lang.Override
  public long getLimitedCount() {
    return limitedCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (searchTaskCount_ != 0L) {
      output.writeInt64(1, searchTaskCount_);
    }
    if (searchShardTaskCount_ != 0L) {
      output.writeInt64(2, searchShardTaskCount_);
    }
    if (cancellationCount_ != 0L) {
      output.writeInt64(3, cancellationCount_);
    }
    if (limitedCount_ != 0L) {
      output.writeInt64(4, limitedCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (searchTaskCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, searchTaskCount_);
    }
    if (searchShardTaskCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, searchShardTaskCount_);
    }
    if (cancellationCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, cancellationCount_);
    }
    if (limitedCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, limitedCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opensearch.protobufs.services.SearchBackpressureMetrics)) {
      return super.equals(obj);
    }
    org.opensearch.protobufs.services.SearchBackpressureMetrics other = (org.opensearch.protobufs.services.SearchBackpressureMetrics) obj;

    if (getSearchTaskCount()
        != other.getSearchTaskCount()) return false;
    if (getSearchShardTaskCount()
        != other.getSearchShardTaskCount()) return false;
    if (getCancellationCount()
        != other.getCancellationCount()) return false;
    if (getLimitedCount()
        != other.getLimitedCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SEARCH_TASK_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSearchTaskCount());
    hash = (37 * hash) + SEARCH_SHARD_TASK_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSearchShardTaskCount());
    hash = (37 * hash) + CANCELLATION_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCancellationCount());
    hash = (37 * hash) + LIMITED_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLimitedCount());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opensearch.protobufs.services.SearchBackpressureMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.SearchBackpressureMetrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.SearchBackpressureMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.SearchBackpressureMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.SearchBackpressureMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.SearchBackpressureMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.SearchBackpressureMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.SearchBackpressureMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.opensearch.protobufs.services.SearchBackpressureMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.opensearch.protobufs.services.SearchBackpressureMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.SearchBackpressureMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.SearchBackpressureMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opensearch.protobufs.services.SearchBackpressureMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.opensearch.protobufs.services.SearchBackpressureMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.opensearch.protobufs.services.SearchBackpressureMetrics)
      org.opensearch.protobufs.services.SearchBackpressureMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_SearchBackpressureMetrics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_SearchBackpressureMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opensearch.protobufs.services.SearchBackpressureMetrics.class, org.opensearch.protobufs.services.SearchBackpressureMetrics.Builder.class);
    }

    // Construct using org.opensearch.protobufs.services.SearchBackpressureMetrics.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      searchTaskCount_ = 0L;
      searchShardTaskCount_ = 0L;
      cancellationCount_ = 0L;
      limitedCount_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_SearchBackpressureMetrics_descriptor;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.SearchBackpressureMetrics getDefaultInstanceForType() {
      return org.opensearch.protobufs.services.SearchBackpressureMetrics.getDefaultInstance();
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.SearchBackpressureMetrics build() {
      org.opensearch.protobufs.services.SearchBackpressureMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.SearchBackpressureMetrics buildPartial() {
      org.opensearch.protobufs.services.SearchBackpressureMetrics result = new org.opensearch.protobufs.services.SearchBackpressureMetrics(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.opensearch.protobufs.services.SearchBackpressureMetrics result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.searchTaskCount_ = searchTaskCount_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.searchShardTaskCount_ = searchShardTaskCount_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.cancellationCount_ = cancellationCount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.limitedCount_ = limitedCount_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opensearch.protobufs.services.SearchBackpressureMetrics) {
        return mergeFrom((org.opensearch.protobufs.services.SearchBackpressureMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opensearch.protobufs.services.SearchBackpressureMetrics other) {
      if (other == org.opensearch.protobufs.services.SearchBackpressureMetrics.getDefaultInstance()) return this;
      if (other.getSearchTaskCount() != 0L) {
        setSearchTaskCount(other.getSearchTaskCount());
      }
      if (other.getSearchShardTaskCount() != 0L) {
        setSearchShardTaskCount(other.getSearchShardTaskCount());
      }
      if (other.getCancellationCount() != 0L) {
        setCancellationCount(other.getCancellationCount());
      }
      if (other.getLimitedCount() != 0L) {
        setLimitedCount(other.getLimitedCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              searchTaskCount_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              searchShardTaskCount_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              cancellationCount_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              limitedCount_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long searchTaskCount_ ;
    /**
     * <code>int64 search_task_count = 1 [json_name = "searchTaskCount"];</code>
     * @return The searchTaskCount.
     */
    @java.lang.Override
    public long getSearchTaskCount() {
      return searchTaskCount_;
    }
    /**
     * <code>int64 search_task_count = 1 [json_name = "searchTaskCount"];</code>
     * @param value The searchTaskCount to set.
     * @return This builder for chaining.
     */
    public Builder setSearchTaskCount(long value) {

      searchTaskCount_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 search_task_count = 1 [json_name = "searchTaskCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSearchTaskCount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      searchTaskCount_ = 0L;
      onChanged();
      return this;
    }

    private long searchShardTaskCount_ ;
    /**
     * <code>int64 search_shard_task_count = 2 [json_name = "searchShardTaskCount"];</code>
     * @return The searchShardTaskCount.
     */
    @java.lang.Override
    public long getSearchShardTaskCount() {
      return searchShardTaskCount_;
    }
    /**
     * <code>int64 search_shard_task_count = 2 [json_name = "searchShardTaskCount"];</code>
     * @param value The searchShardTaskCount to set.
     * @return This builder for chaining.
     */
    public Builder setSearchShardTaskCount(long value) {

      searchShardTaskCount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 search_shard_task_count = 2 [json_name = "searchShardTaskCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSearchShardTaskCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      searchShardTaskCount_ = 0L;
      onChanged();
      return this;
    }

    private long cancellationCount_ ;
    /**
     * <code>int64 cancellation_count = 3 [json_name = "cancellationCount"];</code>
     * @return The cancellationCount.
     */
    @java.lang.Override
    public long getCancellationCount() {
      return cancellationCount_;
    }
    /**
     * <code>int64 cancellation_count = 3 [json_name = "cancellationCount"];</code>
     * @param value The cancellationCount to set.
     * @return This builder for chaining.
     */
    public Builder setCancellationCount(long value) {

      cancellationCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 cancellation_count = 3 [json_name = "cancellationCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCancellationCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cancellationCount_ = 0L;
      onChanged();
      return this;
    }

    private long limitedCount_ ;
    /**
     * <code>int64 limited_count = 4 [json_name = "limitedCount"];</code>
     * @return The limitedCount.
     */
    @java.lang.Override
    public long getLimitedCount() {
      return limitedCount_;
    }
    /**
     * <code>int64 limited_count = 4 [json_name = "limitedCount"];</code>
     * @param value The limitedCount to set.
     * @return This builder for chaining.
     */
    public Builder setLimitedCount(long value) {

      limitedCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 limited_count = 4 [json_name = "limitedCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLimitedCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      limitedCount_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.opensearch.protobufs.services.SearchBackpressureMetrics)
  }

  // @@protoc_insertion_point(class_scope:org.opensearch.protobufs.services.SearchBackpressureMetrics)
  private static final org.opensearch.protobufs.services.SearchBackpressureMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opensearch.protobufs.services.SearchBackpressureMetrics();
  }

  public static org.opensearch.protobufs.services.SearchBackpressureMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchBackpressureMetrics>
      PARSER = new com.google.protobuf.AbstractParser<SearchBackpressureMetrics>() {
    @java.lang.Override
    public SearchBackpressureMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SearchBackpressureMetrics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchBackpressureMetrics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opensearch.protobufs.services.SearchBackpressureMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

