// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

public interface SearchBackpressureMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opensearch.protobufs.services.SearchBackpressureMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 search_task_count = 1 [json_name = "searchTaskCount"];</code>
   * @return The searchTaskCount.
   */
  long getSearchTaskCount();

  /**
   * <code>int64 search_shard_task_count = 2 [json_name = "searchShardTaskCount"];</code>
   * @return The searchShardTaskCount.
   */
  long getSearchShardTaskCount();

  /**
   * <code>int64 cancellation_count = 3 [json_name = "cancellationCount"];</code>
   * @return The cancellationCount.
   */
  long getCancellationCount();

  /**
   * <code>int64 limited_count = 4 [json_name = "limitedCount"];</code>
   * @return The limitedCount.
   */
  long getLimitedCount();
}
