// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

public interface StreamMetricsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opensearch.protobufs.services.StreamMetricsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
   * @return A list containing the categories.
   */
  java.util.List<org.opensearch.protobufs.services.MetricCategory> getCategoriesList();
  /**
   * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
   * @return The count of categories.
   */
  int getCategoriesCount();
  /**
   * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
   * @param index The index of the element to return.
   * @return The categories at the given index.
   */
  org.opensearch.protobufs.services.MetricCategory getCategories(int index);
  /**
   * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
   * @return A list containing the enum numeric values on the wire for categories.
   */
  java.util.List<java.lang.Integer>
  getCategoriesValueList();
  /**
   * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of categories at the given index.
   */
  int getCategoriesValue(int index);

  /**
   * <code>int32 interval_seconds = 2 [json_name = "intervalSeconds"];</code>
   * @return The intervalSeconds.
   */
  int getIntervalSeconds();

  /**
   * <code>bool delta_mode = 3 [json_name = "deltaMode"];</code>
   * @return The deltaMode.
   */
  boolean getDeltaMode();

  /**
   * <code>float change_threshold = 4 [json_name = "changeThreshold"];</code>
   * @return The changeThreshold.
   */
  float getChangeThreshold();
}
