// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

/**
 * Protobuf type {@code org.opensearch.protobufs.services.StreamMetricsRequest}
 */
public final class StreamMetricsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.opensearch.protobufs.services.StreamMetricsRequest)
    StreamMetricsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamMetricsRequest.newBuilder() to construct.
  private StreamMetricsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamMetricsRequest() {
    categories_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamMetricsRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_StreamMetricsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_StreamMetricsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opensearch.protobufs.services.StreamMetricsRequest.class, org.opensearch.protobufs.services.StreamMetricsRequest.Builder.class);
  }

  public static final int CATEGORIES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<java.lang.Integer> categories_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, org.opensearch.protobufs.services.MetricCategory> categories_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, org.opensearch.protobufs.services.MetricCategory>() {
            public org.opensearch.protobufs.services.MetricCategory convert(java.lang.Integer from) {
              org.opensearch.protobufs.services.MetricCategory result = org.opensearch.protobufs.services.MetricCategory.forNumber(from);
              return result == null ? org.opensearch.protobufs.services.MetricCategory.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
   * @return A list containing the categories.
   */
  @java.lang.Override
  public java.util.List<org.opensearch.protobufs.services.MetricCategory> getCategoriesList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, org.opensearch.protobufs.services.MetricCategory>(categories_, categories_converter_);
  }
  /**
   * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
   * @return The count of categories.
   */
  @java.lang.Override
  public int getCategoriesCount() {
    return categories_.size();
  }
  /**
   * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
   * @param index The index of the element to return.
   * @return The categories at the given index.
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.MetricCategory getCategories(int index) {
    return categories_converter_.convert(categories_.get(index));
  }
  /**
   * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
   * @return A list containing the enum numeric values on the wire for categories.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getCategoriesValueList() {
    return categories_;
  }
  /**
   * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of categories at the given index.
   */
  @java.lang.Override
  public int getCategoriesValue(int index) {
    return categories_.get(index);
  }
  private int categoriesMemoizedSerializedSize;

  public static final int INTERVAL_SECONDS_FIELD_NUMBER = 2;
  private int intervalSeconds_ = 0;
  /**
   * <code>int32 interval_seconds = 2 [json_name = "intervalSeconds"];</code>
   * @return The intervalSeconds.
   */
  @java.lang.Override
  public int getIntervalSeconds() {
    return intervalSeconds_;
  }

  public static final int DELTA_MODE_FIELD_NUMBER = 3;
  private boolean deltaMode_ = false;
  /**
   * <code>bool delta_mode = 3 [json_name = "deltaMode"];</code>
   * @return The deltaMode.
   */
  @java.lang.Override
  public boolean getDeltaMode() {
    return deltaMode_;
  }

  public static final int CHANGE_THRESHOLD_FIELD_NUMBER = 4;
  private float changeThreshold_ = 0F;
  /**
   * <code>float change_threshold = 4 [json_name = "changeThreshold"];</code>
   * @return The changeThreshold.
   */
  @java.lang.Override
  public float getChangeThreshold() {
    return changeThreshold_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getCategoriesList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(categoriesMemoizedSerializedSize);
    }
    for (int i = 0; i < categories_.size(); i++) {
      output.writeEnumNoTag(categories_.get(i));
    }
    if (intervalSeconds_ != 0) {
      output.writeInt32(2, intervalSeconds_);
    }
    if (deltaMode_ != false) {
      output.writeBool(3, deltaMode_);
    }
    if (java.lang.Float.floatToRawIntBits(changeThreshold_) != 0) {
      output.writeFloat(4, changeThreshold_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < categories_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(categories_.get(i));
      }
      size += dataSize;
      if (!getCategoriesList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }categoriesMemoizedSerializedSize = dataSize;
    }
    if (intervalSeconds_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, intervalSeconds_);
    }
    if (deltaMode_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, deltaMode_);
    }
    if (java.lang.Float.floatToRawIntBits(changeThreshold_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, changeThreshold_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opensearch.protobufs.services.StreamMetricsRequest)) {
      return super.equals(obj);
    }
    org.opensearch.protobufs.services.StreamMetricsRequest other = (org.opensearch.protobufs.services.StreamMetricsRequest) obj;

    if (!categories_.equals(other.categories_)) return false;
    if (getIntervalSeconds()
        != other.getIntervalSeconds()) return false;
    if (getDeltaMode()
        != other.getDeltaMode()) return false;
    if (java.lang.Float.floatToIntBits(getChangeThreshold())
        != java.lang.Float.floatToIntBits(
            other.getChangeThreshold())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCategoriesCount() > 0) {
      hash = (37 * hash) + CATEGORIES_FIELD_NUMBER;
      hash = (53 * hash) + categories_.hashCode();
    }
    hash = (37 * hash) + INTERVAL_SECONDS_FIELD_NUMBER;
    hash = (53 * hash) + getIntervalSeconds();
    hash = (37 * hash) + DELTA_MODE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDeltaMode());
    hash = (37 * hash) + CHANGE_THRESHOLD_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getChangeThreshold());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opensearch.protobufs.services.StreamMetricsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.StreamMetricsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.StreamMetricsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.StreamMetricsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.StreamMetricsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.StreamMetricsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.StreamMetricsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.StreamMetricsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.opensearch.protobufs.services.StreamMetricsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.opensearch.protobufs.services.StreamMetricsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.StreamMetricsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.StreamMetricsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opensearch.protobufs.services.StreamMetricsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.opensearch.protobufs.services.StreamMetricsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.opensearch.protobufs.services.StreamMetricsRequest)
      org.opensearch.protobufs.services.StreamMetricsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_StreamMetricsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_StreamMetricsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opensearch.protobufs.services.StreamMetricsRequest.class, org.opensearch.protobufs.services.StreamMetricsRequest.Builder.class);
    }

    // Construct using org.opensearch.protobufs.services.StreamMetricsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      categories_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      intervalSeconds_ = 0;
      deltaMode_ = false;
      changeThreshold_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_StreamMetricsRequest_descriptor;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.StreamMetricsRequest getDefaultInstanceForType() {
      return org.opensearch.protobufs.services.StreamMetricsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.StreamMetricsRequest build() {
      org.opensearch.protobufs.services.StreamMetricsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.StreamMetricsRequest buildPartial() {
      org.opensearch.protobufs.services.StreamMetricsRequest result = new org.opensearch.protobufs.services.StreamMetricsRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.opensearch.protobufs.services.StreamMetricsRequest result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        categories_ = java.util.Collections.unmodifiableList(categories_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.categories_ = categories_;
    }

    private void buildPartial0(org.opensearch.protobufs.services.StreamMetricsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.intervalSeconds_ = intervalSeconds_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.deltaMode_ = deltaMode_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.changeThreshold_ = changeThreshold_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opensearch.protobufs.services.StreamMetricsRequest) {
        return mergeFrom((org.opensearch.protobufs.services.StreamMetricsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opensearch.protobufs.services.StreamMetricsRequest other) {
      if (other == org.opensearch.protobufs.services.StreamMetricsRequest.getDefaultInstance()) return this;
      if (!other.categories_.isEmpty()) {
        if (categories_.isEmpty()) {
          categories_ = other.categories_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCategoriesIsMutable();
          categories_.addAll(other.categories_);
        }
        onChanged();
      }
      if (other.getIntervalSeconds() != 0) {
        setIntervalSeconds(other.getIntervalSeconds());
      }
      if (other.getDeltaMode() != false) {
        setDeltaMode(other.getDeltaMode());
      }
      if (other.getChangeThreshold() != 0F) {
        setChangeThreshold(other.getChangeThreshold());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int tmpRaw = input.readEnum();
              ensureCategoriesIsMutable();
              categories_.add(tmpRaw);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int tmpRaw = input.readEnum();
                ensureCategoriesIsMutable();
                categories_.add(tmpRaw);
              }
              input.popLimit(oldLimit);
              break;
            } // case 10
            case 16: {
              intervalSeconds_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              deltaMode_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 37: {
              changeThreshold_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> categories_ =
      java.util.Collections.emptyList();
    private void ensureCategoriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        categories_ = new java.util.ArrayList<java.lang.Integer>(categories_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
     * @return A list containing the categories.
     */
    public java.util.List<org.opensearch.protobufs.services.MetricCategory> getCategoriesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, org.opensearch.protobufs.services.MetricCategory>(categories_, categories_converter_);
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
     * @return The count of categories.
     */
    public int getCategoriesCount() {
      return categories_.size();
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
     * @param index The index of the element to return.
     * @return The categories at the given index.
     */
    public org.opensearch.protobufs.services.MetricCategory getCategories(int index) {
      return categories_converter_.convert(categories_.get(index));
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
     * @param index The index to set the value at.
     * @param value The categories to set.
     * @return This builder for chaining.
     */
    public Builder setCategories(
        int index, org.opensearch.protobufs.services.MetricCategory value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCategoriesIsMutable();
      categories_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
     * @param value The categories to add.
     * @return This builder for chaining.
     */
    public Builder addCategories(org.opensearch.protobufs.services.MetricCategory value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCategoriesIsMutable();
      categories_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
     * @param values The categories to add.
     * @return This builder for chaining.
     */
    public Builder addAllCategories(
        java.lang.Iterable<? extends org.opensearch.protobufs.services.MetricCategory> values) {
      ensureCategoriesIsMutable();
      for (org.opensearch.protobufs.services.MetricCategory value : values) {
        categories_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCategories() {
      categories_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
     * @return A list containing the enum numeric values on the wire for categories.
     */
    public java.util.List<java.lang.Integer>
    getCategoriesValueList() {
      return java.util.Collections.unmodifiableList(categories_);
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of categories at the given index.
     */
    public int getCategoriesValue(int index) {
      return categories_.get(index);
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for categories to set.
     * @return This builder for chaining.
     */
    public Builder setCategoriesValue(
        int index, int value) {
      ensureCategoriesIsMutable();
      categories_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
     * @param value The enum numeric value on the wire for categories to add.
     * @return This builder for chaining.
     */
    public Builder addCategoriesValue(int value) {
      ensureCategoriesIsMutable();
      categories_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.MetricCategory categories = 1 [json_name = "categories"];</code>
     * @param values The enum numeric values on the wire for categories to add.
     * @return This builder for chaining.
     */
    public Builder addAllCategoriesValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureCategoriesIsMutable();
      for (int value : values) {
        categories_.add(value);
      }
      onChanged();
      return this;
    }

    private int intervalSeconds_ ;
    /**
     * <code>int32 interval_seconds = 2 [json_name = "intervalSeconds"];</code>
     * @return The intervalSeconds.
     */
    @java.lang.Override
    public int getIntervalSeconds() {
      return intervalSeconds_;
    }
    /**
     * <code>int32 interval_seconds = 2 [json_name = "intervalSeconds"];</code>
     * @param value The intervalSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setIntervalSeconds(int value) {

      intervalSeconds_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 interval_seconds = 2 [json_name = "intervalSeconds"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIntervalSeconds() {
      bitField0_ = (bitField0_ & ~0x00000002);
      intervalSeconds_ = 0;
      onChanged();
      return this;
    }

    private boolean deltaMode_ ;
    /**
     * <code>bool delta_mode = 3 [json_name = "deltaMode"];</code>
     * @return The deltaMode.
     */
    @java.lang.Override
    public boolean getDeltaMode() {
      return deltaMode_;
    }
    /**
     * <code>bool delta_mode = 3 [json_name = "deltaMode"];</code>
     * @param value The deltaMode to set.
     * @return This builder for chaining.
     */
    public Builder setDeltaMode(boolean value) {

      deltaMode_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool delta_mode = 3 [json_name = "deltaMode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeltaMode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      deltaMode_ = false;
      onChanged();
      return this;
    }

    private float changeThreshold_ ;
    /**
     * <code>float change_threshold = 4 [json_name = "changeThreshold"];</code>
     * @return The changeThreshold.
     */
    @java.lang.Override
    public float getChangeThreshold() {
      return changeThreshold_;
    }
    /**
     * <code>float change_threshold = 4 [json_name = "changeThreshold"];</code>
     * @param value The changeThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setChangeThreshold(float value) {

      changeThreshold_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float change_threshold = 4 [json_name = "changeThreshold"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChangeThreshold() {
      bitField0_ = (bitField0_ & ~0x00000008);
      changeThreshold_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.opensearch.protobufs.services.StreamMetricsRequest)
  }

  // @@protoc_insertion_point(class_scope:org.opensearch.protobufs.services.StreamMetricsRequest)
  private static final org.opensearch.protobufs.services.StreamMetricsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opensearch.protobufs.services.StreamMetricsRequest();
  }

  public static org.opensearch.protobufs.services.StreamMetricsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamMetricsRequest>
      PARSER = new com.google.protobuf.AbstractParser<StreamMetricsRequest>() {
    @java.lang.Override
    public StreamMetricsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamMetricsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamMetricsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opensearch.protobufs.services.StreamMetricsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

