// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

public interface ThreadPoolMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opensearch.protobufs.services.ThreadPoolMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
   */
  java.util.List<org.opensearch.protobufs.services.ThreadPoolStats> 
      getPoolsList();
  /**
   * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
   */
  org.opensearch.protobufs.services.ThreadPoolStats getPools(int index);
  /**
   * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
   */
  int getPoolsCount();
  /**
   * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
   */
  java.util.List<? extends org.opensearch.protobufs.services.ThreadPoolStatsOrBuilder> 
      getPoolsOrBuilderList();
  /**
   * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
   */
  org.opensearch.protobufs.services.ThreadPoolStatsOrBuilder getPoolsOrBuilder(
      int index);
}
