// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

/**
 * Protobuf type {@code org.opensearch.protobufs.services.ThreadPoolStats}
 */
public final class ThreadPoolStats extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.opensearch.protobufs.services.ThreadPoolStats)
    ThreadPoolStatsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ThreadPoolStats.newBuilder() to construct.
  private ThreadPoolStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ThreadPoolStats() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ThreadPoolStats();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_ThreadPoolStats_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_ThreadPoolStats_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opensearch.protobufs.services.ThreadPoolStats.class, org.opensearch.protobufs.services.ThreadPoolStats.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int THREADS_FIELD_NUMBER = 2;
  private int threads_ = 0;
  /**
   * <code>int32 threads = 2 [json_name = "threads"];</code>
   * @return The threads.
   */
  @java.lang.Override
  public int getThreads() {
    return threads_;
  }

  public static final int QUEUE_FIELD_NUMBER = 3;
  private int queue_ = 0;
  /**
   * <code>int32 queue = 3 [json_name = "queue"];</code>
   * @return The queue.
   */
  @java.lang.Override
  public int getQueue() {
    return queue_;
  }

  public static final int ACTIVE_FIELD_NUMBER = 4;
  private int active_ = 0;
  /**
   * <code>int32 active = 4 [json_name = "active"];</code>
   * @return The active.
   */
  @java.lang.Override
  public int getActive() {
    return active_;
  }

  public static final int REJECTED_FIELD_NUMBER = 5;
  private long rejected_ = 0L;
  /**
   * <code>int64 rejected = 5 [json_name = "rejected"];</code>
   * @return The rejected.
   */
  @java.lang.Override
  public long getRejected() {
    return rejected_;
  }

  public static final int LARGEST_FIELD_NUMBER = 6;
  private int largest_ = 0;
  /**
   * <code>int32 largest = 6 [json_name = "largest"];</code>
   * @return The largest.
   */
  @java.lang.Override
  public int getLargest() {
    return largest_;
  }

  public static final int COMPLETED_FIELD_NUMBER = 7;
  private long completed_ = 0L;
  /**
   * <code>int64 completed = 7 [json_name = "completed"];</code>
   * @return The completed.
   */
  @java.lang.Override
  public long getCompleted() {
    return completed_;
  }

  public static final int WAIT_TIME_NANOS_FIELD_NUMBER = 8;
  private long waitTimeNanos_ = 0L;
  /**
   * <code>int64 wait_time_nanos = 8 [json_name = "waitTimeNanos"];</code>
   * @return The waitTimeNanos.
   */
  @java.lang.Override
  public long getWaitTimeNanos() {
    return waitTimeNanos_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (threads_ != 0) {
      output.writeInt32(2, threads_);
    }
    if (queue_ != 0) {
      output.writeInt32(3, queue_);
    }
    if (active_ != 0) {
      output.writeInt32(4, active_);
    }
    if (rejected_ != 0L) {
      output.writeInt64(5, rejected_);
    }
    if (largest_ != 0) {
      output.writeInt32(6, largest_);
    }
    if (completed_ != 0L) {
      output.writeInt64(7, completed_);
    }
    if (waitTimeNanos_ != 0L) {
      output.writeInt64(8, waitTimeNanos_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (threads_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, threads_);
    }
    if (queue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, queue_);
    }
    if (active_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, active_);
    }
    if (rejected_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, rejected_);
    }
    if (largest_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, largest_);
    }
    if (completed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, completed_);
    }
    if (waitTimeNanos_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, waitTimeNanos_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opensearch.protobufs.services.ThreadPoolStats)) {
      return super.equals(obj);
    }
    org.opensearch.protobufs.services.ThreadPoolStats other = (org.opensearch.protobufs.services.ThreadPoolStats) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getThreads()
        != other.getThreads()) return false;
    if (getQueue()
        != other.getQueue()) return false;
    if (getActive()
        != other.getActive()) return false;
    if (getRejected()
        != other.getRejected()) return false;
    if (getLargest()
        != other.getLargest()) return false;
    if (getCompleted()
        != other.getCompleted()) return false;
    if (getWaitTimeNanos()
        != other.getWaitTimeNanos()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + THREADS_FIELD_NUMBER;
    hash = (53 * hash) + getThreads();
    hash = (37 * hash) + QUEUE_FIELD_NUMBER;
    hash = (53 * hash) + getQueue();
    hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + getActive();
    hash = (37 * hash) + REJECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRejected());
    hash = (37 * hash) + LARGEST_FIELD_NUMBER;
    hash = (53 * hash) + getLargest();
    hash = (37 * hash) + COMPLETED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCompleted());
    hash = (37 * hash) + WAIT_TIME_NANOS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWaitTimeNanos());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opensearch.protobufs.services.ThreadPoolStats parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.ThreadPoolStats parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.ThreadPoolStats parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.ThreadPoolStats parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.ThreadPoolStats parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.ThreadPoolStats parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.ThreadPoolStats parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.ThreadPoolStats parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.opensearch.protobufs.services.ThreadPoolStats parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.opensearch.protobufs.services.ThreadPoolStats parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.ThreadPoolStats parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.ThreadPoolStats parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opensearch.protobufs.services.ThreadPoolStats prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.opensearch.protobufs.services.ThreadPoolStats}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.opensearch.protobufs.services.ThreadPoolStats)
      org.opensearch.protobufs.services.ThreadPoolStatsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_ThreadPoolStats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_ThreadPoolStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opensearch.protobufs.services.ThreadPoolStats.class, org.opensearch.protobufs.services.ThreadPoolStats.Builder.class);
    }

    // Construct using org.opensearch.protobufs.services.ThreadPoolStats.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      threads_ = 0;
      queue_ = 0;
      active_ = 0;
      rejected_ = 0L;
      largest_ = 0;
      completed_ = 0L;
      waitTimeNanos_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_ThreadPoolStats_descriptor;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.ThreadPoolStats getDefaultInstanceForType() {
      return org.opensearch.protobufs.services.ThreadPoolStats.getDefaultInstance();
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.ThreadPoolStats build() {
      org.opensearch.protobufs.services.ThreadPoolStats result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.ThreadPoolStats buildPartial() {
      org.opensearch.protobufs.services.ThreadPoolStats result = new org.opensearch.protobufs.services.ThreadPoolStats(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.opensearch.protobufs.services.ThreadPoolStats result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.threads_ = threads_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.queue_ = queue_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.active_ = active_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.rejected_ = rejected_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.largest_ = largest_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.completed_ = completed_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.waitTimeNanos_ = waitTimeNanos_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opensearch.protobufs.services.ThreadPoolStats) {
        return mergeFrom((org.opensearch.protobufs.services.ThreadPoolStats)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opensearch.protobufs.services.ThreadPoolStats other) {
      if (other == org.opensearch.protobufs.services.ThreadPoolStats.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getThreads() != 0) {
        setThreads(other.getThreads());
      }
      if (other.getQueue() != 0) {
        setQueue(other.getQueue());
      }
      if (other.getActive() != 0) {
        setActive(other.getActive());
      }
      if (other.getRejected() != 0L) {
        setRejected(other.getRejected());
      }
      if (other.getLargest() != 0) {
        setLargest(other.getLargest());
      }
      if (other.getCompleted() != 0L) {
        setCompleted(other.getCompleted());
      }
      if (other.getWaitTimeNanos() != 0L) {
        setWaitTimeNanos(other.getWaitTimeNanos());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              threads_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              queue_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              active_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              rejected_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              largest_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              completed_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              waitTimeNanos_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int threads_ ;
    /**
     * <code>int32 threads = 2 [json_name = "threads"];</code>
     * @return The threads.
     */
    @java.lang.Override
    public int getThreads() {
      return threads_;
    }
    /**
     * <code>int32 threads = 2 [json_name = "threads"];</code>
     * @param value The threads to set.
     * @return This builder for chaining.
     */
    public Builder setThreads(int value) {

      threads_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 threads = 2 [json_name = "threads"];</code>
     * @return This builder for chaining.
     */
    public Builder clearThreads() {
      bitField0_ = (bitField0_ & ~0x00000002);
      threads_ = 0;
      onChanged();
      return this;
    }

    private int queue_ ;
    /**
     * <code>int32 queue = 3 [json_name = "queue"];</code>
     * @return The queue.
     */
    @java.lang.Override
    public int getQueue() {
      return queue_;
    }
    /**
     * <code>int32 queue = 3 [json_name = "queue"];</code>
     * @param value The queue to set.
     * @return This builder for chaining.
     */
    public Builder setQueue(int value) {

      queue_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 queue = 3 [json_name = "queue"];</code>
     * @return This builder for chaining.
     */
    public Builder clearQueue() {
      bitField0_ = (bitField0_ & ~0x00000004);
      queue_ = 0;
      onChanged();
      return this;
    }

    private int active_ ;
    /**
     * <code>int32 active = 4 [json_name = "active"];</code>
     * @return The active.
     */
    @java.lang.Override
    public int getActive() {
      return active_;
    }
    /**
     * <code>int32 active = 4 [json_name = "active"];</code>
     * @param value The active to set.
     * @return This builder for chaining.
     */
    public Builder setActive(int value) {

      active_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 active = 4 [json_name = "active"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActive() {
      bitField0_ = (bitField0_ & ~0x00000008);
      active_ = 0;
      onChanged();
      return this;
    }

    private long rejected_ ;
    /**
     * <code>int64 rejected = 5 [json_name = "rejected"];</code>
     * @return The rejected.
     */
    @java.lang.Override
    public long getRejected() {
      return rejected_;
    }
    /**
     * <code>int64 rejected = 5 [json_name = "rejected"];</code>
     * @param value The rejected to set.
     * @return This builder for chaining.
     */
    public Builder setRejected(long value) {

      rejected_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 rejected = 5 [json_name = "rejected"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRejected() {
      bitField0_ = (bitField0_ & ~0x00000010);
      rejected_ = 0L;
      onChanged();
      return this;
    }

    private int largest_ ;
    /**
     * <code>int32 largest = 6 [json_name = "largest"];</code>
     * @return The largest.
     */
    @java.lang.Override
    public int getLargest() {
      return largest_;
    }
    /**
     * <code>int32 largest = 6 [json_name = "largest"];</code>
     * @param value The largest to set.
     * @return This builder for chaining.
     */
    public Builder setLargest(int value) {

      largest_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 largest = 6 [json_name = "largest"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLargest() {
      bitField0_ = (bitField0_ & ~0x00000020);
      largest_ = 0;
      onChanged();
      return this;
    }

    private long completed_ ;
    /**
     * <code>int64 completed = 7 [json_name = "completed"];</code>
     * @return The completed.
     */
    @java.lang.Override
    public long getCompleted() {
      return completed_;
    }
    /**
     * <code>int64 completed = 7 [json_name = "completed"];</code>
     * @param value The completed to set.
     * @return This builder for chaining.
     */
    public Builder setCompleted(long value) {

      completed_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 completed = 7 [json_name = "completed"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCompleted() {
      bitField0_ = (bitField0_ & ~0x00000040);
      completed_ = 0L;
      onChanged();
      return this;
    }

    private long waitTimeNanos_ ;
    /**
     * <code>int64 wait_time_nanos = 8 [json_name = "waitTimeNanos"];</code>
     * @return The waitTimeNanos.
     */
    @java.lang.Override
    public long getWaitTimeNanos() {
      return waitTimeNanos_;
    }
    /**
     * <code>int64 wait_time_nanos = 8 [json_name = "waitTimeNanos"];</code>
     * @param value The waitTimeNanos to set.
     * @return This builder for chaining.
     */
    public Builder setWaitTimeNanos(long value) {

      waitTimeNanos_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 wait_time_nanos = 8 [json_name = "waitTimeNanos"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWaitTimeNanos() {
      bitField0_ = (bitField0_ & ~0x00000080);
      waitTimeNanos_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.opensearch.protobufs.services.ThreadPoolStats)
  }

  // @@protoc_insertion_point(class_scope:org.opensearch.protobufs.services.ThreadPoolStats)
  private static final org.opensearch.protobufs.services.ThreadPoolStats DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opensearch.protobufs.services.ThreadPoolStats();
  }

  public static org.opensearch.protobufs.services.ThreadPoolStats getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ThreadPoolStats>
      PARSER = new com.google.protobuf.AbstractParser<ThreadPoolStats>() {
    @java.lang.Override
    public ThreadPoolStats parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ThreadPoolStats> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ThreadPoolStats> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opensearch.protobufs.services.ThreadPoolStats getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

