// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

/**
 * Protobuf type {@code org.opensearch.protobufs.services.ThreadPoolMetrics}
 */
public final class ThreadPoolMetrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.opensearch.protobufs.services.ThreadPoolMetrics)
    ThreadPoolMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ThreadPoolMetrics.newBuilder() to construct.
  private ThreadPoolMetrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ThreadPoolMetrics() {
    pools_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ThreadPoolMetrics();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_ThreadPoolMetrics_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_ThreadPoolMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opensearch.protobufs.services.ThreadPoolMetrics.class, org.opensearch.protobufs.services.ThreadPoolMetrics.Builder.class);
  }

  public static final int POOLS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.opensearch.protobufs.services.ThreadPoolStats> pools_;
  /**
   * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
   */
  @java.lang.Override
  public java.util.List<org.opensearch.protobufs.services.ThreadPoolStats> getPoolsList() {
    return pools_;
  }
  /**
   * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.opensearch.protobufs.services.ThreadPoolStatsOrBuilder> 
      getPoolsOrBuilderList() {
    return pools_;
  }
  /**
   * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
   */
  @java.lang.Override
  public int getPoolsCount() {
    return pools_.size();
  }
  /**
   * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.ThreadPoolStats getPools(int index) {
    return pools_.get(index);
  }
  /**
   * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
   */
  @java.lang.Override
  public org.opensearch.protobufs.services.ThreadPoolStatsOrBuilder getPoolsOrBuilder(
      int index) {
    return pools_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < pools_.size(); i++) {
      output.writeMessage(1, pools_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < pools_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, pools_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opensearch.protobufs.services.ThreadPoolMetrics)) {
      return super.equals(obj);
    }
    org.opensearch.protobufs.services.ThreadPoolMetrics other = (org.opensearch.protobufs.services.ThreadPoolMetrics) obj;

    if (!getPoolsList()
        .equals(other.getPoolsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPoolsCount() > 0) {
      hash = (37 * hash) + POOLS_FIELD_NUMBER;
      hash = (53 * hash) + getPoolsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opensearch.protobufs.services.ThreadPoolMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.ThreadPoolMetrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.ThreadPoolMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.ThreadPoolMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.ThreadPoolMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opensearch.protobufs.services.ThreadPoolMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.ThreadPoolMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.ThreadPoolMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.opensearch.protobufs.services.ThreadPoolMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.opensearch.protobufs.services.ThreadPoolMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opensearch.protobufs.services.ThreadPoolMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opensearch.protobufs.services.ThreadPoolMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opensearch.protobufs.services.ThreadPoolMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.opensearch.protobufs.services.ThreadPoolMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.opensearch.protobufs.services.ThreadPoolMetrics)
      org.opensearch.protobufs.services.ThreadPoolMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_ThreadPoolMetrics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_ThreadPoolMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opensearch.protobufs.services.ThreadPoolMetrics.class, org.opensearch.protobufs.services.ThreadPoolMetrics.Builder.class);
    }

    // Construct using org.opensearch.protobufs.services.ThreadPoolMetrics.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (poolsBuilder_ == null) {
        pools_ = java.util.Collections.emptyList();
      } else {
        pools_ = null;
        poolsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opensearch.protobufs.services.MetricsServiceProto.internal_static_org_opensearch_protobufs_services_ThreadPoolMetrics_descriptor;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.ThreadPoolMetrics getDefaultInstanceForType() {
      return org.opensearch.protobufs.services.ThreadPoolMetrics.getDefaultInstance();
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.ThreadPoolMetrics build() {
      org.opensearch.protobufs.services.ThreadPoolMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opensearch.protobufs.services.ThreadPoolMetrics buildPartial() {
      org.opensearch.protobufs.services.ThreadPoolMetrics result = new org.opensearch.protobufs.services.ThreadPoolMetrics(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.opensearch.protobufs.services.ThreadPoolMetrics result) {
      if (poolsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          pools_ = java.util.Collections.unmodifiableList(pools_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pools_ = pools_;
      } else {
        result.pools_ = poolsBuilder_.build();
      }
    }

    private void buildPartial0(org.opensearch.protobufs.services.ThreadPoolMetrics result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opensearch.protobufs.services.ThreadPoolMetrics) {
        return mergeFrom((org.opensearch.protobufs.services.ThreadPoolMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opensearch.protobufs.services.ThreadPoolMetrics other) {
      if (other == org.opensearch.protobufs.services.ThreadPoolMetrics.getDefaultInstance()) return this;
      if (poolsBuilder_ == null) {
        if (!other.pools_.isEmpty()) {
          if (pools_.isEmpty()) {
            pools_ = other.pools_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePoolsIsMutable();
            pools_.addAll(other.pools_);
          }
          onChanged();
        }
      } else {
        if (!other.pools_.isEmpty()) {
          if (poolsBuilder_.isEmpty()) {
            poolsBuilder_.dispose();
            poolsBuilder_ = null;
            pools_ = other.pools_;
            bitField0_ = (bitField0_ & ~0x00000001);
            poolsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPoolsFieldBuilder() : null;
          } else {
            poolsBuilder_.addAllMessages(other.pools_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.opensearch.protobufs.services.ThreadPoolStats m =
                  input.readMessage(
                      org.opensearch.protobufs.services.ThreadPoolStats.parser(),
                      extensionRegistry);
              if (poolsBuilder_ == null) {
                ensurePoolsIsMutable();
                pools_.add(m);
              } else {
                poolsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.opensearch.protobufs.services.ThreadPoolStats> pools_ =
      java.util.Collections.emptyList();
    private void ensurePoolsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        pools_ = new java.util.ArrayList<org.opensearch.protobufs.services.ThreadPoolStats>(pools_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.opensearch.protobufs.services.ThreadPoolStats, org.opensearch.protobufs.services.ThreadPoolStats.Builder, org.opensearch.protobufs.services.ThreadPoolStatsOrBuilder> poolsBuilder_;

    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public java.util.List<org.opensearch.protobufs.services.ThreadPoolStats> getPoolsList() {
      if (poolsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pools_);
      } else {
        return poolsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public int getPoolsCount() {
      if (poolsBuilder_ == null) {
        return pools_.size();
      } else {
        return poolsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public org.opensearch.protobufs.services.ThreadPoolStats getPools(int index) {
      if (poolsBuilder_ == null) {
        return pools_.get(index);
      } else {
        return poolsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public Builder setPools(
        int index, org.opensearch.protobufs.services.ThreadPoolStats value) {
      if (poolsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePoolsIsMutable();
        pools_.set(index, value);
        onChanged();
      } else {
        poolsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public Builder setPools(
        int index, org.opensearch.protobufs.services.ThreadPoolStats.Builder builderForValue) {
      if (poolsBuilder_ == null) {
        ensurePoolsIsMutable();
        pools_.set(index, builderForValue.build());
        onChanged();
      } else {
        poolsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public Builder addPools(org.opensearch.protobufs.services.ThreadPoolStats value) {
      if (poolsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePoolsIsMutable();
        pools_.add(value);
        onChanged();
      } else {
        poolsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public Builder addPools(
        int index, org.opensearch.protobufs.services.ThreadPoolStats value) {
      if (poolsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePoolsIsMutable();
        pools_.add(index, value);
        onChanged();
      } else {
        poolsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public Builder addPools(
        org.opensearch.protobufs.services.ThreadPoolStats.Builder builderForValue) {
      if (poolsBuilder_ == null) {
        ensurePoolsIsMutable();
        pools_.add(builderForValue.build());
        onChanged();
      } else {
        poolsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public Builder addPools(
        int index, org.opensearch.protobufs.services.ThreadPoolStats.Builder builderForValue) {
      if (poolsBuilder_ == null) {
        ensurePoolsIsMutable();
        pools_.add(index, builderForValue.build());
        onChanged();
      } else {
        poolsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public Builder addAllPools(
        java.lang.Iterable<? extends org.opensearch.protobufs.services.ThreadPoolStats> values) {
      if (poolsBuilder_ == null) {
        ensurePoolsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pools_);
        onChanged();
      } else {
        poolsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public Builder clearPools() {
      if (poolsBuilder_ == null) {
        pools_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        poolsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public Builder removePools(int index) {
      if (poolsBuilder_ == null) {
        ensurePoolsIsMutable();
        pools_.remove(index);
        onChanged();
      } else {
        poolsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public org.opensearch.protobufs.services.ThreadPoolStats.Builder getPoolsBuilder(
        int index) {
      return getPoolsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public org.opensearch.protobufs.services.ThreadPoolStatsOrBuilder getPoolsOrBuilder(
        int index) {
      if (poolsBuilder_ == null) {
        return pools_.get(index);  } else {
        return poolsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public java.util.List<? extends org.opensearch.protobufs.services.ThreadPoolStatsOrBuilder> 
         getPoolsOrBuilderList() {
      if (poolsBuilder_ != null) {
        return poolsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pools_);
      }
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public org.opensearch.protobufs.services.ThreadPoolStats.Builder addPoolsBuilder() {
      return getPoolsFieldBuilder().addBuilder(
          org.opensearch.protobufs.services.ThreadPoolStats.getDefaultInstance());
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public org.opensearch.protobufs.services.ThreadPoolStats.Builder addPoolsBuilder(
        int index) {
      return getPoolsFieldBuilder().addBuilder(
          index, org.opensearch.protobufs.services.ThreadPoolStats.getDefaultInstance());
    }
    /**
     * <code>repeated .org.opensearch.protobufs.services.ThreadPoolStats pools = 1 [json_name = "pools"];</code>
     */
    public java.util.List<org.opensearch.protobufs.services.ThreadPoolStats.Builder> 
         getPoolsBuilderList() {
      return getPoolsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.opensearch.protobufs.services.ThreadPoolStats, org.opensearch.protobufs.services.ThreadPoolStats.Builder, org.opensearch.protobufs.services.ThreadPoolStatsOrBuilder> 
        getPoolsFieldBuilder() {
      if (poolsBuilder_ == null) {
        poolsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.opensearch.protobufs.services.ThreadPoolStats, org.opensearch.protobufs.services.ThreadPoolStats.Builder, org.opensearch.protobufs.services.ThreadPoolStatsOrBuilder>(
                pools_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        pools_ = null;
      }
      return poolsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.opensearch.protobufs.services.ThreadPoolMetrics)
  }

  // @@protoc_insertion_point(class_scope:org.opensearch.protobufs.services.ThreadPoolMetrics)
  private static final org.opensearch.protobufs.services.ThreadPoolMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opensearch.protobufs.services.ThreadPoolMetrics();
  }

  public static org.opensearch.protobufs.services.ThreadPoolMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ThreadPoolMetrics>
      PARSER = new com.google.protobuf.AbstractParser<ThreadPoolMetrics>() {
    @java.lang.Override
    public ThreadPoolMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ThreadPoolMetrics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ThreadPoolMetrics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opensearch.protobufs.services.ThreadPoolMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

