// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/services/metrics_service.proto

// Protobuf Java Version: 3.25.8
package org.opensearch.protobufs.services;

public interface ThreadPoolStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opensearch.protobufs.services.ThreadPoolStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 threads = 2 [json_name = "threads"];</code>
   * @return The threads.
   */
  int getThreads();

  /**
   * <code>int32 queue = 3 [json_name = "queue"];</code>
   * @return The queue.
   */
  int getQueue();

  /**
   * <code>int32 active = 4 [json_name = "active"];</code>
   * @return The active.
   */
  int getActive();

  /**
   * <code>int64 rejected = 5 [json_name = "rejected"];</code>
   * @return The rejected.
   */
  long getRejected();

  /**
   * <code>int32 largest = 6 [json_name = "largest"];</code>
   * @return The largest.
   */
  int getLargest();

  /**
   * <code>int64 completed = 7 [json_name = "completed"];</code>
   * @return The completed.
   */
  long getCompleted();

  /**
   * <code>int64 wait_time_nanos = 8 [json_name = "waitTimeNanos"];</code>
   * @return The waitTimeNanos.
   */
  long getWaitTimeNanos();
}
