# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from opensearch.protobufs.services import metrics_service_pb2 as protos_dot_services_dot_metrics__service__pb2


class MetricsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamNodeMetrics = channel.unary_stream(
                '/org.opensearch.protobufs.services.MetricsService/StreamNodeMetrics',
                request_serializer=protos_dot_services_dot_metrics__service__pb2.StreamMetricsRequest.SerializeToString,
                response_deserializer=protos_dot_services_dot_metrics__service__pb2.NodeMetricsSnapshot.FromString,
                _registered_method=True)


class MetricsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamNodeMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetricsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamNodeMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamNodeMetrics,
                    request_deserializer=protos_dot_services_dot_metrics__service__pb2.StreamMetricsRequest.FromString,
                    response_serializer=protos_dot_services_dot_metrics__service__pb2.NodeMetricsSnapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.opensearch.protobufs.services.MetricsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org.opensearch.protobufs.services.MetricsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetricsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamNodeMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/org.opensearch.protobufs.services.MetricsService/StreamNodeMetrics',
            protos_dot_services_dot_metrics__service__pb2.StreamMetricsRequest.SerializeToString,
            protos_dot_services_dot_metrics__service__pb2.NodeMetricsSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
